import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireRole } from '@/lib/session'

export const dynamic = 'force-dynamic'

export async function GET() {
  const guard = await requireRole(['ADMIN'])
  if (guard.error) return NextResponse.json({ error: guard.error }, { status: guard.status })

  try {
    const now = new Date()
    const monthStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1))
    const monthEnd = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1))
    const in7 = new Date(now)
    in7.setDate(in7.getDate() + 7)

    const [
      propertiesCount,
      clientsCount,
      activeRes,
      openPayoutsAgg,
      paidPayoutsAgg,
      paidSubscriptionsAgg,
      overdueTasks,
      upcomingCheckIns,
      upcomingCheckOuts,
      leadsOpen,
      pendingInvoicesAgg,
    ] = await Promise.all([
      prisma.property.count(),
      prisma.user.count({ where: { role: 'CLIENT' } }),
      prisma.reservation.count({ where: { status: { in: ['UPCOMING', 'ACTIVE'] } } }),
      prisma.payout.aggregate({
        _sum: { netAmount: true, commission: true },
        _count: true,
        where: { status: 'SCHEDULED' },
      }),
      // Rental commissions + gross from payouts paid this month
      prisma.payout.aggregate({
        _sum: { grossAmount: true, commission: true },
        where: { status: 'PAID', paidAt: { gte: monthStart, lt: monthEnd } },
      }),
      // Manually-created invoices paid this month (subscription fees, adjustments, etc.)
      prisma.paymentReceipt.aggregate({
        _sum: { grossAmount: true },
        _count: true,
        where: {
          isAutoGenerated: false,
          status: 'PAID',
          paidAt: { gte: monthStart, lt: monthEnd },
        },
      }),
      prisma.task.count({
        where: { status: { not: 'COMPLETED' }, dueDate: { lt: now } },
      }),
      prisma.reservation.findMany({
        where: { checkIn: { gte: now, lt: in7 } },
        include: { property: { select: { name: true, city: true } } },
        orderBy: { checkIn: 'asc' },
        take: 10,
      }),
      prisma.reservation.findMany({
        where: { checkOut: { gte: now, lt: in7 } },
        include: { property: { select: { name: true, city: true } } },
        orderBy: { checkOut: 'asc' },
        take: 10,
      }),
      prisma.lead.count({ where: { status: { in: ['NEW', 'CONTACTED', 'QUALIFIED'] } } }),
      prisma.paymentReceipt.aggregate({
        _sum: { grossAmount: true },
        _count: true,
        where: { status: 'PENDING' },
      }),
    ])

    const rentalVolume     = paidPayoutsAgg._sum.grossAmount ?? 0
    const rentalCommission = paidPayoutsAgg._sum.commission ?? 0
    const invoiceRevenue   = Number(paidSubscriptionsAgg._sum?.grossAmount ?? 0)
    const totalHMRevenue   = rentalCommission + invoiceRevenue

    return NextResponse.json({
      propertiesCount,
      clientsCount,
      activeReservations: activeRes,
      rentalVolume,
      rentalCommission,
      invoiceRevenue,
      totalHMRevenue,
      openPayouts: {
        count: openPayoutsAgg._count,
        net: openPayoutsAgg._sum.netAmount ?? 0,
        commission: openPayoutsAgg._sum.commission ?? 0,
      },
      overdueTasks,
      upcomingCheckIns,
      upcomingCheckOuts,
      leadsOpen,
      pendingInvoices: {
        count: pendingInvoicesAgg._count,
        total: Number(pendingInvoicesAgg._sum?.grossAmount ?? 0),
      },
    })
  } catch (err) {
    console.error('[admin/stats] error:', err)
    return NextResponse.json({ error: 'stats failed' }, { status: 500 })
  }
}
