-- Add isAutoGenerated flag to Invoice
-- Existing rows (including auto-generated) get false; payout route will set true going forward
ALTER TABLE "Invoice" ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;
