import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireRole } from '@/lib/session'
import {
  PLAN_MONTHLY_FEE,
  calcManagerEarnings,
  DEFAULT_MANAGER_SUBSCRIPTION_SHARE,
  DEFAULT_MANAGER_COMMISSION_SHARE,
} from '@/lib/finance'

/**
 * GET /api/reports/summary?period=current|previous
 *
 * Returns role-scoped report data:
 * - ADMIN: full platform metrics + comparison
 * - MANAGER: own client portfolio + personal commission
 * - CLIENT: own properties performance
 */
export async function GET(request: NextRequest) {
  const guard = await requireRole(['ADMIN', 'MANAGER', 'CLIENT'])
  if (guard.error) return NextResponse.json({ error: guard.error }, { status: guard.status })
  const me = guard.user!

  const period = request.nextUrl.searchParams.get('period') ?? 'current'
  const now = new Date()

  // Period ranges
  let periodStart: Date, periodEnd: Date, prevStart: Date, prevEnd: Date

  if (period === 'previous') {
    periodStart = new Date(now.getFullYear(), now.getMonth() - 1, 1)
    periodEnd = new Date(now.getFullYear(), now.getMonth(), 1)
    prevStart = new Date(now.getFullYear(), now.getMonth() - 2, 1)
    prevEnd = periodStart
  } else {
    periodStart = new Date(now.getFullYear(), now.getMonth(), 1)
    periodEnd = now
    prevStart = new Date(now.getFullYear(), now.getMonth() - 1, 1)
    prevEnd = periodStart
  }

  const periodLabel = periodStart.toLocaleDateString('pt-PT', { month: 'long', year: 'numeric' })
  const prevLabel = prevStart.toLocaleDateString('pt-PT', { month: 'long', year: 'numeric' })

  if (me.role === 'ADMIN') return NextResponse.json(await buildAdminReport(periodStart, periodEnd, prevStart, prevEnd, periodLabel, prevLabel))
  if (me.role === 'MANAGER') return NextResponse.json(await buildManagerReport(me.id, periodStart, periodEnd, prevStart, prevEnd, periodLabel, prevLabel))
  return NextResponse.json(await buildClientReport(me.id, periodStart, periodEnd, prevStart, prevEnd, periodLabel, prevLabel))
}

async function buildAdminReport(start: Date, end: Date, prevStart: Date, prevEnd: Date, label: string, prevLabel: string) {
  const [current, previous] = await Promise.all([
    getAdminPeriodData(start, end),
    getAdminPeriodData(prevStart, prevEnd),
  ])

  return {
    role: 'ADMIN',
    period: label,
    previousPeriod: prevLabel,
    current,
    previous,
    delta: {
      grossRevenue: pctChange(current.grossRevenue, previous.grossRevenue),
      hmCommission: pctChange(current.hmCommission, previous.hmCommission),
      reservations: pctChange(current.reservations, previous.reservations),
      avgPrice: pctChange(current.avgPricePerNight, previous.avgPricePerNight),
      occupancyNights: pctChange(current.totalNights, previous.totalNights),
    },
  }
}

async function getAdminPeriodData(start: Date, end: Date) {
  const [paidPayouts, reservations, activeProps, clients, invoiceRevenue] = await Promise.all([
    prisma.payout.aggregate({
      where: { status: 'PAID', paidAt: { gte: start, lt: end } },
      _sum: { grossAmount: true, commission: true, netAmount: true },
      _count: true,
    }),
    prisma.reservation.findMany({
      where: { checkIn: { gte: start, lt: end }, status: { not: 'CANCELLED' } },
      select: { amount: true, checkIn: true, checkOut: true },
    }),
    prisma.property.count({ where: { status: 'ACTIVE' } }),
    prisma.user.count({ where: { role: 'CLIENT' } }),
    prisma.invoice.aggregate({
      where: { status: 'PAID', isAutoGenerated: false, paidAt: { gte: start, lt: end } },
      _sum: { amount: true },
    }),
  ])

  const totalNights = reservations.reduce((s, r) => s + Math.max(1, Math.ceil((r.checkOut.getTime() - r.checkIn.getTime()) / 86400000)), 0)
  const grossRevenue = paidPayouts._sum.grossAmount ?? 0
  const hmCommission = paidPayouts._sum.commission ?? 0
  const invoicePaid = invoiceRevenue._sum.amount ?? 0

  return {
    grossRevenue: +grossRevenue.toFixed(2),
    hmCommission: +hmCommission.toFixed(2),
    hmTotalRevenue: +(hmCommission + invoicePaid).toFixed(2),
    invoiceRevenue: +invoicePaid.toFixed(2),
    netToOwners: +(paidPayouts._sum.netAmount ?? 0).toFixed(2),
    payoutCount: paidPayouts._count,
    reservations: reservations.length,
    totalNights,
    avgPricePerNight: totalNights > 0 ? +(reservations.reduce((s, r) => s + r.amount, 0) / totalNights).toFixed(0) : 0,
    activeProperties: activeProps,
    totalClients: clients,
  }
}

async function buildManagerReport(managerId: string, start: Date, end: Date, prevStart: Date, prevEnd: Date, label: string, prevLabel: string) {
  // Get manager's compensation config
  const manager = await prisma.user.findUnique({
    where: { id: managerId },
    select: { name: true, managerSubscriptionShare: true, managerCommissionShare: true },
  })

  const subShare = manager?.managerSubscriptionShare ?? DEFAULT_MANAGER_SUBSCRIPTION_SHARE
  const comShare = manager?.managerCommissionShare ?? DEFAULT_MANAGER_COMMISSION_SHARE

  const [current, previous] = await Promise.all([
    getManagerPeriodData(managerId, start, end, subShare, comShare),
    getManagerPeriodData(managerId, prevStart, prevEnd, subShare, comShare),
  ])

  return {
    role: 'MANAGER',
    managerName: manager?.name ?? '',
    period: label,
    previousPeriod: prevLabel,
    compensationRates: {
      subscriptionShare: subShare,
      commissionShare: comShare,
    },
    current,
    previous,
    delta: {
      grossRevenue: pctChange(current.grossRevenue, previous.grossRevenue),
      managerTotal: pctChange(current.managerEarnings.total, previous.managerEarnings.total),
      clientCount: pctChange(current.clientCount, previous.clientCount),
      reservations: pctChange(current.reservations, previous.reservations),
    },
  }
}

async function getManagerPeriodData(managerId: string, start: Date, end: Date, subShare: number, comShare: number) {
  const clients = await prisma.user.findMany({
    where: { managerId, role: 'CLIENT' },
    select: { id: true, name: true, subscriptionPlan: true },
  })
  const clientIds = clients.map(c => c.id)

  const [paidPayouts, reservations] = await Promise.all([
    prisma.payout.aggregate({
      where: { status: 'PAID', paidAt: { gte: start, lt: end }, property: { ownerId: { in: clientIds } } },
      _sum: { grossAmount: true, commission: true, netAmount: true },
      _count: true,
    }),
    prisma.reservation.count({
      where: { checkIn: { gte: start, lt: end }, status: { not: 'CANCELLED' }, property: { ownerId: { in: clientIds } } },
    }),
  ])

  const grossRevenue = paidPayouts._sum.grossAmount ?? 0

  // Monthly subscription fees from clients
  const subscriptionFees = clients.reduce((s, c) => s + (PLAN_MONTHLY_FEE[c.subscriptionPlan ?? ''] ?? 0), 0)

  const managerEarnings = calcManagerEarnings({
    grossRevenue,
    subscriptionFees,
    subscriptionShare: subShare,
    commissionShare: comShare,
  })

  return {
    clientCount: clients.length,
    clients: clients.map(c => ({ name: c.name, plan: c.subscriptionPlan })),
    grossRevenue: +grossRevenue.toFixed(2),
    hmCommission: +(paidPayouts._sum.commission ?? 0).toFixed(2),
    netToOwners: +(paidPayouts._sum.netAmount ?? 0).toFixed(2),
    reservations,
    subscriptionFees,
    managerEarnings,
  }
}

async function buildClientReport(clientId: string, start: Date, end: Date, prevStart: Date, prevEnd: Date, label: string, prevLabel: string) {
  const [current, previous] = await Promise.all([
    getClientPeriodData(clientId, start, end),
    getClientPeriodData(clientId, prevStart, prevEnd),
  ])

  return {
    role: 'CLIENT',
    period: label,
    previousPeriod: prevLabel,
    current,
    previous,
    delta: {
      grossRevenue: pctChange(current.grossRevenue, previous.grossRevenue),
      netReceived: pctChange(current.netReceived, previous.netReceived),
      reservations: pctChange(current.reservations, previous.reservations),
      occupancy: pctChange(current.occupancy, previous.occupancy),
    },
  }
}

async function getClientPeriodData(clientId: string, start: Date, end: Date) {
  const [properties, paidPayouts, reservations] = await Promise.all([
    prisma.property.findMany({
      where: { ownerId: clientId },
      select: { id: true, name: true, status: true },
    }),
    prisma.payout.aggregate({
      where: { status: 'PAID', paidAt: { gte: start, lt: end }, property: { ownerId: clientId } },
      _sum: { grossAmount: true, commission: true, netAmount: true },
      _count: true,
    }),
    prisma.reservation.findMany({
      where: { checkIn: { gte: start, lt: end }, status: { not: 'CANCELLED' }, property: { ownerId: clientId } },
      select: { amount: true, checkIn: true, checkOut: true, property: { select: { name: true } } },
    }),
  ])

  const totalNights = reservations.reduce((s, r) => s + Math.max(1, Math.ceil((r.checkOut.getTime() - r.checkIn.getTime()) / 86400000)), 0)
  const daysInPeriod = Math.max(1, Math.ceil((end.getTime() - start.getTime()) / 86400000))
  const occupancy = properties.length > 0 ? Math.min(100, (totalNights / (daysInPeriod * properties.length)) * 100) : 0

  return {
    properties: properties.map(p => ({ name: p.name, status: p.status })),
    grossRevenue: +(paidPayouts._sum.grossAmount ?? 0).toFixed(2),
    commission: +(paidPayouts._sum.commission ?? 0).toFixed(2),
    netReceived: +(paidPayouts._sum.netAmount ?? 0).toFixed(2),
    reservations: reservations.length,
    totalNights,
    occupancy: +occupancy.toFixed(0),
    avgPricePerNight: totalNights > 0 ? +(reservations.reduce((s, r) => s + r.amount, 0) / totalNights).toFixed(0) : 0,
  }
}

function pctChange(current: number, previous: number): number | null {
  if (previous === 0) return current > 0 ? 100 : null
  return +((current - previous) / previous * 100).toFixed(1)
}
