/**
 * AI Analysis — uses Claude Haiku to analyze HIGH/CRITICAL alerts
 * and suggest concrete fixes.
 */
import Anthropic from '@anthropic-ai/sdk'
import type { CheckResult } from './checks'

const client = process.env.ANTHROPIC_API_KEY
  ? new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
  : null

const SYSTEM_PROMPT = `You are a senior software engineer at HostMasters, a SaaS B2B for short-term rental property management.

Your job: analyze a detected anomaly and suggest a concrete, actionable fix for the admin.

Context about HostMasters:
- Next.js 14 + Prisma + PostgreSQL
- Business entities: User, Property, Reservation, Payout, Invoice, Task, Lead, TaxObligation
- Payouts: grossAmount = commission + netAmount (always). commissionRate depends on owner plan.
- Invoices: isAutoGenerated=true created when payout marked PAID. Have paidAt when status=PAID.
- Roles: ADMIN, MANAGER, CREW, CLIENT

Response format (plain text, 3 short paragraphs max):
1. **Likely cause** — what probably happened
2. **Impact** — who is affected and how
3. **Suggested fix** — concrete action (SQL, API call, or admin UI step)

Be specific. No generic advice. Portuguese.`

export async function analyzeAlert(check: CheckResult): Promise<string | null> {
  if (!client) return null

  try {
    const msg = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 500,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: `Alerta detectado:
- Tipo: ${check.checkType}
- Severidade: ${check.severity}
- Mensagem: ${check.message}
- Quantidade afectada: ${check.count}
${check.details ? `- Detalhes: ${JSON.stringify(check.details).slice(0, 500)}` : ''}

Analisa e sugere o fix.`,
        },
      ],
    })

    const text = msg.content
      .filter(block => block.type === 'text')
      .map(block => (block as { text: string }).text)
      .join('\n')

    return text.trim() || null
  } catch (err) {
    console.error('[AI Monitor] Analysis failed:', err)
    return null
  }
}
