/**
 * AI Monitor — check definitions
 *
 * Each check returns a { checkType, severity, message, count, details? }
 * when an anomaly is detected, or null when everything is fine.
 *
 * Severity:
 *   CRITICAL — imediata acção, afecta dinheiro ou segurança
 *   HIGH     — requer acção do admin em <24h
 *   MEDIUM   — operacional, não-bloqueante
 *   LOW      — informativo, nice-to-have
 */
import { prisma } from '@/lib/prisma'
import { PLAN_COMMISSION } from '@/lib/finance'

export type CheckSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'

export type CheckResult = {
  checkType: string
  severity: CheckSeverity
  message: string
  count: number
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  details?: Record<string, any>
  canAutoFix?: boolean
}

export type CheckFn = (now: Date) => Promise<CheckResult | null>

// ─────────────────────────────────────────────────────────────────
// CATEGORY: RESERVATIONS
// ─────────────────────────────────────────────────────────────────

const r1_overdueCheckins: CheckFn = async (now) => {
  const count = await prisma.reservation.count({
    where: { status: 'UPCOMING', checkIn: { lt: now } },
  })
  if (count === 0) return null
  return {
    checkType: 'RESERVATION_PAST_CHECKIN',
    severity: 'HIGH',
    message: `${count} reserva(s) com estado UPCOMING mas check-in já passou`,
    count,
  }
}

const r2_checkinsWithoutTask: CheckFn = async (now) => {
  const in7Days = new Date(now.getTime() + 7 * 24 * 3600 * 1000)
  const upcomingCheckIns = await prisma.reservation.findMany({
    where: { checkIn: { gte: now, lte: in7Days }, status: { in: ['UPCOMING', 'ACTIVE'] } },
    select: { id: true, propertyId: true },
  })
  if (upcomingCheckIns.length === 0) return null
  const propIds = Array.from(new Set(upcomingCheckIns.map(r => r.propertyId)))
  const existingTasks = await prisma.task.findMany({
    where: { type: 'CHECK_IN', propertyId: { in: propIds }, dueDate: { gte: now, lte: in7Days }, status: { not: 'COMPLETED' } },
    select: { propertyId: true },
  })
  const covered = new Set(existingTasks.map(t => t.propertyId))
  const missing = upcomingCheckIns.filter(r => !covered.has(r.propertyId)).length
  if (missing === 0) return null
  return {
    checkType: 'CHECKIN_NO_TASK',
    severity: 'MEDIUM',
    message: `${missing} reserva(s) com check-in em <7 dias sem tarefa CHECK_IN`,
    count: missing,
  }
}

const r5_zeroAmountReservations: CheckFn = async () => {
  const count = await prisma.reservation.count({
    where: { amount: 0, status: { not: 'CANCELLED' } },
  })
  if (count === 0) return null
  return {
    checkType: 'RESERVATION_ZERO_AMOUNT',
    severity: 'MEDIUM',
    message: `${count} reserva(s) activa(s) com valor €0`,
    count,
  }
}

const r_overlappingReservations: CheckFn = async () => {
  // Find reservations that overlap on the same property (excluding CANCELLED)
  const overlaps = await prisma.$queryRaw<{ count: bigint }[]>`
    SELECT COUNT(*)::bigint AS count FROM (
      SELECT r1.id
      FROM "Reservation" r1
      JOIN "Reservation" r2 ON r1."propertyId" = r2."propertyId" AND r1.id < r2.id
      WHERE r1.status != 'CANCELLED' AND r2.status != 'CANCELLED'
        AND r1."checkIn" < r2."checkOut" AND r2."checkIn" < r1."checkOut"
    ) AS overlaps
  `
  const count = Number(overlaps[0]?.count ?? 0)
  if (count === 0) return null
  return {
    checkType: 'RESERVATION_OVERLAP',
    severity: 'CRITICAL',
    message: `${count} par(es) de reservas sobrepostas na mesma propriedade`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: PAYOUTS & INVOICES
// ─────────────────────────────────────────────────────────────────

const p1_paidPayoutsNoInvoice: CheckFn = async () => {
  const paidPayoutsCount = await prisma.payout.count({ where: { status: 'PAID' } })
  const autoInvoicesCount = await prisma.paymentReceipt.count({ where: { isAutoGenerated: true, status: 'PAID' } })
  const missing = Math.max(0, paidPayoutsCount - autoInvoicesCount)
  if (missing === 0) return null
  return {
    checkType: 'PAYOUT_NO_INVOICE',
    severity: 'HIGH',
    message: `${missing} payout(s) pago(s) sem invoice auto-gerado`,
    count: missing,
  }
}

const p1b_duplicateInvoices: CheckFn = async () => {
  const paidPayoutsCount = await prisma.payout.count({ where: { status: 'PAID' } })
  const autoInvoicesCount = await prisma.paymentReceipt.count({ where: { isAutoGenerated: true, status: 'PAID' } })
  const duplicates = Math.max(0, autoInvoicesCount - paidPayoutsCount)
  if (duplicates === 0) return null
  return {
    checkType: 'INVOICE_DUPLICATE',
    severity: 'CRITICAL',
    message: `${duplicates} invoice(s) auto-gerado(s) a mais que payouts pagos — possível duplicação`,
    count: duplicates,
  }
}

const p2_overduePayouts: CheckFn = async (now) => {
  const count = await prisma.payout.count({
    where: { status: 'SCHEDULED', scheduledFor: { lt: now } },
  })
  if (count === 0) return null
  return {
    checkType: 'PAYOUT_OVERDUE',
    severity: 'HIGH',
    message: `${count} payout(s) em atraso — data agendada já passou`,
    count,
  }
}

const p3_commissionMismatch: CheckFn = async () => {
  const scheduledPayouts = await prisma.payout.findMany({
    where: { status: 'SCHEDULED' },
    select: { id: true, commissionRate: true, property: { select: { owner: { select: { subscriptionPlan: true } } } } },
  })
  const mismatched = scheduledPayouts.filter(p => {
    const plan = p.property?.owner?.subscriptionPlan
    if (!plan) return false
    return Math.abs(p.commissionRate - (PLAN_COMMISSION[plan] ?? 0) * 100) > 0.1
  })
  if (mismatched.length === 0) return null
  return {
    checkType: 'COMMISSION_MISMATCH',
    severity: 'MEDIUM',
    message: `${mismatched.length} payout(s) com taxa diferente do plano actual do proprietário`,
    count: mismatched.length,
    details: { payoutIds: mismatched.map(p => p.id).slice(0, 50) },
    canAutoFix: true,
  }
}

const p4_invoicesNoPaidAt: CheckFn = async () => {
  const count = await prisma.paymentReceipt.count({ where: { status: 'PAID', paidAt: null } })
  if (count === 0) return null
  return {
    checkType: 'INVOICE_PAID_NO_PAIDAT',
    severity: 'HIGH',
    message: `${count} invoice(s) PAID sem data de pagamento — invisíveis no dashboard`,
    count,
    canAutoFix: true,
  }
}

const p5_financialIntegrity: CheckFn = async () => {
  // gross = commission + net should always hold. Find violations.
  const violations = await prisma.$queryRaw<{ count: bigint }[]>`
    SELECT COUNT(*)::bigint AS count FROM "Payout"
    WHERE ABS("grossAmount" - "commission" - "netAmount") > 0.01
  `
  const count = Number(violations[0]?.count ?? 0)
  if (count === 0) return null
  return {
    checkType: 'PAYOUT_MATH_MISMATCH',
    severity: 'CRITICAL',
    message: `${count} payout(s) com gross ≠ commission + net — erro aritmético`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: PROPERTIES
// ─────────────────────────────────────────────────────────────────

const prop_stale: CheckFn = async (now) => {
  const ninetyDaysAgo = new Date(now.getTime() - 90 * 24 * 3600 * 1000)
  const count = await prisma.property.count({
    where: { status: 'ACTIVE', reservations: { none: { checkIn: { gte: ninetyDaysAgo } } } },
  })
  if (count === 0) return null
  return {
    checkType: 'PROPERTY_STALE',
    severity: 'LOW',
    message: `${count} propriedade(s) activa(s) sem reservas há 90+ dias`,
    count,
  }
}

const prop_activeNoOwner: CheckFn = async () => {
  // ownerId is required in schema; check via raw query for safety / historical records
  const result = await prisma.$queryRaw<{ count: bigint }[]>`
    SELECT COUNT(*)::bigint AS count FROM "Property"
    WHERE status = 'ACTIVE' AND "ownerId" IS NULL
  `
  const count = Number(result[0]?.count ?? 0)
  if (count === 0) return null
  return {
    checkType: 'PROPERTY_ACTIVE_NO_OWNER',
    severity: 'CRITICAL',
    message: `${count} propriedade(s) ACTIVE sem proprietário — dados órfãos`,
    count,
  }
}

const prop_activeNoPhotos: CheckFn = async () => {
  const props = await prisma.property.findMany({
    where: { status: 'ACTIVE' },
    select: { id: true, photos: true },
  })
  const count = props.filter(p => !p.photos || p.photos.length === 0).length
  if (count === 0) return null
  return {
    checkType: 'PROPERTY_NO_PHOTOS',
    severity: 'MEDIUM',
    message: `${count} propriedade(s) ACTIVE sem fotos`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: USERS & ROLES
// ─────────────────────────────────────────────────────────────────

const u_duplicateEmails: CheckFn = async () => {
  // Schema makes email unique, but belt-and-braces check (case-insensitive dups):
  const dupes = await prisma.$queryRaw<{ email: string; n: bigint }[]>`
    SELECT LOWER(email) AS email, COUNT(*)::bigint AS n
    FROM "User"
    GROUP BY LOWER(email)
    HAVING COUNT(*) > 1
  `
  if (dupes.length === 0) return null
  return {
    checkType: 'USER_DUPLICATE_EMAIL',
    severity: 'HIGH',
    message: `${dupes.length} email(s) duplicado(s) (case-insensitive) no modelo User`,
    count: dupes.length,
    details: { examples: dupes.slice(0, 5) },
  }
}

const u_clientsWithoutManager: CheckFn = async () => {
  const count = await prisma.user.count({
    where: { role: 'CLIENT', managerId: null },
  })
  if (count === 0) return null
  return {
    checkType: 'CLIENT_NO_MANAGER',
    severity: 'MEDIUM',
    message: `${count} cliente(s) sem manager atribuído`,
    count,
  }
}

const u_managerIdleClients: CheckFn = async () => {
  // Manager with 0 clients
  const managers = await prisma.user.findMany({
    where: { role: 'MANAGER' },
    select: { id: true, _count: { select: { clients: true } } },
  })
  const idle = managers.filter(m => m._count.clients === 0).length
  if (idle === 0) return null
  return {
    checkType: 'MANAGER_NO_CLIENTS',
    severity: 'LOW',
    message: `${idle} manager(s) sem clientes atribuídos`,
    count: idle,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: TASKS
// ─────────────────────────────────────────────────────────────────

const t_unassignedOverdue: CheckFn = async (now) => {
  const count = await prisma.task.count({
    where: { status: { not: 'COMPLETED' }, assigneeId: null, dueDate: { lt: now } },
  })
  if (count === 0) return null
  return {
    checkType: 'TASK_UNASSIGNED_OVERDUE',
    severity: 'HIGH',
    message: `${count} tarefa(s) em atraso sem crew atribuído`,
    count,
  }
}

const t_72hUnassigned: CheckFn = async (now) => {
  const threeDaysAgo = new Date(now.getTime() - 72 * 3600 * 1000)
  const count = await prisma.task.count({
    where: { assigneeId: null, createdAt: { lt: threeDaysAgo }, status: { not: 'COMPLETED' } },
  })
  if (count === 0) return null
  return {
    checkType: 'TASK_72H_UNASSIGNED',
    severity: 'MEDIUM',
    message: `${count} tarefa(s) criadas há >72h sem crew atribuído`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: TAX OBLIGATIONS
// ─────────────────────────────────────────────────────────────────

const tax_overdue: CheckFn = async (now) => {
  const count = await prisma.taxObligation.count({
    where: {
      status: { in: ['NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED'] },
      dueDate: { lt: now },
    },
  })
  if (count === 0) return null
  return {
    checkType: 'TAX_OVERDUE',
    severity: 'HIGH',
    message: `${count} obrigação(ões) fiscal(is) com prazo ultrapassado`,
    count,
  }
}

const tax_dueIn7Days: CheckFn = async (now) => {
  const in7Days = new Date(now.getTime() + 7 * 24 * 3600 * 1000)
  const count = await prisma.taxObligation.count({
    where: {
      status: { in: ['NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED'] },
      dueDate: { gte: now, lte: in7Days },
    },
  })
  if (count === 0) return null
  return {
    checkType: 'TAX_DUE_SOON',
    severity: 'MEDIUM',
    message: `${count} obrigação(ões) fiscal(is) com prazo em <7 dias`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: CRM / LEADS
// ─────────────────────────────────────────────────────────────────

const lead_staleContact: CheckFn = async (now) => {
  const fourteenDaysAgo = new Date(now.getTime() - 14 * 24 * 3600 * 1000)
  const count = await prisma.lead.count({
    where: {
      status: { in: ['NEW', 'CONTACTED'] },
      createdAt: { lt: fourteenDaysAgo },
    },
  })
  if (count === 0) return null
  return {
    checkType: 'LEAD_STALE',
    severity: 'MEDIUM',
    message: `${count} lead(s) parado(s) há >14 dias sem progresso`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: CREW HEALTH
// ─────────────────────────────────────────────────────────────────

const crew_scoreDrop: CheckFn = async () => {
  // Crew whose score dropped 50+ points in the last 30 days
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 3600 * 1000)
  const events = await prisma.crewScoreEvent.findMany({
    where: { createdAt: { gte: thirtyDaysAgo }, delta: { lt: 0 } },
    select: { crewScoreId: true, delta: true },
  })
  const dropByScore: Record<string, number> = {}
  for (const e of events) {
    dropByScore[e.crewScoreId] = (dropByScore[e.crewScoreId] ?? 0) + e.delta
  }
  const severe = Object.entries(dropByScore).filter(([, d]) => d <= -50)
  if (severe.length === 0) return null
  return {
    checkType: 'CREW_SCORE_DROP',
    severity: 'HIGH',
    message: `${severe.length} crew member(s) lost 50+ score points in the last 30 days`,
    count: severe.length,
    details: { crewScoreIds: severe.map(([id]) => id).slice(0, 20) },
  }
}

const crew_suspended: CheckFn = async () => {
  const count = await prisma.crewScore.count({ where: { level: 'SUSPENDED' } })
  if (count === 0) return null
  return {
    checkType: 'CREW_SUSPENDED',
    severity: 'HIGH',
    message: `${count} crew member(s) currently SUSPENDED (score <50) — cannot receive tasks`,
    count,
  }
}

const crew_completionRate: CheckFn = async () => {
  // Crew with totalTasks >= 5 but approval rate < 80%
  const scores = await prisma.crewScore.findMany({
    where: { totalTasks: { gte: 5 } },
    select: { userId: true, totalTasks: true, totalApproved: true, totalRejected: true },
  })
  const lowRate = scores.filter(s => s.totalTasks > 0 && (s.totalApproved / s.totalTasks) < 0.8)
  if (lowRate.length === 0) return null
  return {
    checkType: 'CREW_LOW_APPROVAL_RATE',
    severity: 'MEDIUM',
    message: `${lowRate.length} crew member(s) with <80% task approval rate (5+ tasks)`,
    count: lowRate.length,
    details: { userIds: lowRate.map(s => s.userId).slice(0, 20) },
  }
}

const crew_propertyRisk: CheckFn = async () => {
  // Active risk alerts on crew-property relationships
  const count = await prisma.crewPropertyRelationship.count({
    where: { aiAlertActive: true },
  })
  if (count === 0) return null
  return {
    checkType: 'CREW_PROPERTY_RISK',
    severity: 'HIGH',
    message: `${count} crew-property relationship(s) with active AI risk alert — substitution recommended`,
    count,
  }
}

const crew_payoutStuck: CheckFn = async (now) => {
  // CrewPayouts stuck in PENDING for more than 3 days
  const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 3600 * 1000)
  const count = await prisma.crewPayout.count({
    where: { status: 'PENDING', createdAt: { lt: threeDaysAgo } },
  })
  if (count === 0) return null
  return {
    checkType: 'CREW_PAYOUT_STUCK',
    severity: 'HIGH',
    message: `${count} crew payout(s) stuck in PENDING for 3+ days — crew not paid`,
    count,
  }
}

const crew_interventionsOpen: CheckFn = async (now) => {
  // Interventions open for more than 24h
  const oneDayAgo = new Date(now.getTime() - 24 * 3600 * 1000)
  const count = await prisma.crewIntervention.count({
    where: { status: 'OPEN', createdAt: { lt: oneDayAgo } },
  })
  if (count === 0) return null
  return {
    checkType: 'CREW_INTERVENTION_STALE',
    severity: 'MEDIUM',
    message: `${count} intervention(s) open for 24h+ without resolution`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: STOCK / CONSUMABLES
// ─────────────────────────────────────────────────────────────────

const stock_criticalLow: CheckFn = async () => {
  const lowStockCategories = await prisma.stockLevel.findMany({
    where: { available: { lt: 5 } },
    include: { category: { select: { id: true, name: true } } },
  })
  // Exclude categories with 0 totalItems (unused categories)
  const critical = lowStockCategories.filter(s => s.totalItems > 0)
  if (critical.length === 0) return null
  return {
    checkType: 'STOCK_CRITICAL_LOW',
    severity: 'HIGH',
    message: `${critical.length} consumable category(ies) with <5 available items — restock needed`,
    count: critical.length,
    details: { categories: critical.map(s => ({ id: s.category.id, name: s.category.name, available: s.available })).slice(0, 20) },
  }
}

const stock_laundryStuck: CheckFn = async (now) => {
  // Items stuck in WASHING status for more than 72 hours
  const threeDaysAgo = new Date(now.getTime() - 72 * 3600 * 1000)
  const stuckItems = await prisma.consumableItem.count({
    where: {
      status: 'WASHING',
      updatedAt: { lt: threeDaysAgo },
    },
  })
  if (stuckItems === 0) return null
  return {
    checkType: 'STOCK_LAUNDRY_STUCK',
    severity: 'MEDIUM',
    message: `${stuckItems} consumable item(s) stuck in WASHING status for 72h+ — laundry may be delayed`,
    count: stuckItems,
  }
}

// ─────────────────────────────────────────────────────────────────
// ALL CHECKS REGISTRY
// ─────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────
// CATEGORY: LEAD PIPELINE & AUTOMATION
// ─────────────────────────────────────────────────────────────────

const lead_convertedNoContract: CheckFn = async () => {
  const leads = await prisma.lead.findMany({
    where: { status: 'CONVERTED', convertedUserId: { not: null } },
    select: { convertedUserId: true, name: true },
  })
  let orphaned = 0
  for (const lead of leads) {
    if (!lead.convertedUserId) continue
    const contract = await prisma.contract.findFirst({
      where: { userId: lead.convertedUserId, signedByUser: true },
    })
    if (!contract) orphaned++
  }
  if (orphaned === 0) return null
  return {
    checkType: 'LEAD_CONVERTED_NO_CONTRACT',
    severity: 'HIGH',
    message: `${orphaned} lead(s) marked CONVERTED but client has no signed contract`,
    count: orphaned,
  }
}

const lead_unattributedClients: CheckFn = async () => {
  const clients = await prisma.user.findMany({
    where: { role: 'CLIENT' },
    select: { id: true, email: true },
  })
  let unlinked = 0
  for (const client of clients) {
    const lead = await prisma.lead.findFirst({
      where: { OR: [{ convertedUserId: client.id }, { email: client.email }] },
    })
    if (!lead) unlinked++
  }
  if (unlinked === 0) return null
  return {
    checkType: 'CLIENT_NO_LEAD_RECORD',
    severity: 'MEDIUM',
    message: `${unlinked} client(s) registered without a lead record in CRM pipeline`,
    count: unlinked,
  }
}

const lead_noFollowUp: CheckFn = async (now) => {
  const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 3600 * 1000)
  const count = await prisma.lead.count({
    where: {
      status: { in: ['NEW', 'CONTACTED'] },
      updatedAt: { lt: sevenDaysAgo },
      followUpDate: null,
    },
  })
  if (count === 0) return null
  return {
    checkType: 'LEAD_NO_FOLLOWUP_7D',
    severity: 'MEDIUM',
    message: `${count} lead(s) without follow-up date, inactive for 7+ days`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: PARTNER PROGRAM
// ─────────────────────────────────────────────────────────────────

const partner_payoutOverdue: CheckFn = async (now) => {
  const count = await prisma.partnerPayout.count({
    where: {
      status: 'PENDING',
      holdUntil: { lt: now },
    },
  }).catch(() => 0)
  if (count === 0) return null
  return {
    checkType: 'PARTNER_PAYOUT_OVERDUE',
    severity: 'HIGH',
    message: `${count} partner payout(s) past 30-day hold period — ready to approve`,
    count,
  }
}

const partner_reversalDeadline: CheckFn = async (now) => {
  const in7Days = new Date(now.getTime() + 7 * 24 * 3600 * 1000)
  const count = await prisma.partnerPayout.count({
    where: {
      status: { in: ['PENDING', 'APPROVED'] },
      reversalDeadline: { gte: now, lte: in7Days },
    },
  }).catch(() => 0)
  if (count === 0) return null
  return {
    checkType: 'PARTNER_REVERSAL_DEADLINE_7D',
    severity: 'MEDIUM',
    message: `${count} partner payout(s) approaching 60-day reversal deadline in next 7 days`,
    count,
  }
}

const partner_inactiveWithLeads: CheckFn = async () => {
  const partners = await prisma.partner.findMany({
    where: { status: 'ACTIVE', totalReferrals: 0 },
    select: { id: true },
  }).catch(() => [])
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const count = (partners as any[]).length
  if (count === 0) return null
  return {
    checkType: 'PARTNER_ACTIVE_NO_REFERRALS',
    severity: 'LOW',
    message: `${count} active partner(s) with zero referrals — consider follow-up visit`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: MARKETING PLAN HEALTH
// ─────────────────────────────────────────────────────────────────

const mkt_lowLeadVolume: CheckFn = async (now) => {
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1)
  const dayOfMonth = now.getDate()
  if (dayOfMonth < 15) return null
  const leadsThisMonth = await prisma.lead.count({
    where: { createdAt: { gte: monthStart } },
  })
  if (leadsThisMonth >= 10) return null
  return {
    checkType: 'MKT_LOW_LEAD_VOLUME',
    severity: 'HIGH',
    message: `Only ${leadsThisMonth} leads this month (past day 15) — target is 15-20/month in Phase 1`,
    count: leadsThisMonth,
  }
}

const mkt_lowConversion: CheckFn = async () => {
  const totalLeads = await prisma.lead.count()
  const converted = await prisma.lead.count({ where: { status: 'CONVERTED' } })
  if (totalLeads < 10) return null
  const rate = (converted / totalLeads) * 100
  if (rate >= 5) return null
  return {
    checkType: 'MKT_LOW_CONVERSION_RATE',
    severity: 'MEDIUM',
    message: `Lead conversion rate is ${rate.toFixed(1)}% — target is 10-15% (Phase 1)`,
    count: 1,
    details: { rate: rate.toFixed(1), totalLeads, converted },
  }
}

const mkt_noPartnerReferrals: CheckFn = async (now) => {
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 3600 * 1000)
  const partnerLeads = await prisma.lead.count({
    where: {
      createdAt: { gte: thirtyDaysAgo },
      partnerId: { not: null },
    } as any,
  })
  const totalLeads = await prisma.lead.count({
    where: { createdAt: { gte: thirtyDaysAgo } },
  })
  if (totalLeads < 5) return null
  const pct = (partnerLeads / totalLeads) * 100
  if (pct >= 10) return null
  return {
    checkType: 'MKT_LOW_PARTNER_REFERRALS',
    severity: 'MEDIUM',
    message: `Only ${pct.toFixed(0)}% of leads from partners in last 30 days — target is 15%+`,
    count: partnerLeads,
    details: { percentage: pct.toFixed(1), partnerLeads, totalLeads },
  }
}

const mkt_churnAlert: CheckFn = async (now) => {
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1)
  const churned = await prisma.user.count({
    where: { role: 'CLIENT', subscriptionPlan: null, updatedAt: { gte: monthStart } },
  })
  const active = await prisma.user.count({
    where: { role: 'CLIENT', subscriptionPlan: { not: null } },
  })
  if (active === 0) return null
  const rate = (churned / active) * 100
  if (rate < 5) return null
  return {
    checkType: 'MKT_HIGH_CHURN',
    severity: 'CRITICAL',
    message: `Monthly churn is ${rate.toFixed(1)}% (${churned} lost / ${active} active) — target is <5%`,
    count: churned,
    details: { rate: rate.toFixed(1), churned, active },
  }
}

const mkt_mrrTracking: CheckFn = async () => {
  const planPricing: Record<string, number> = { BASIC: 89, MID: 159, PREMIUM: 269 }
  const planCounts = await prisma.user.groupBy({
    by: ['subscriptionPlan'],
    _count: true,
    where: { role: 'CLIENT', subscriptionPlan: { not: null } },
  })
  const mrr = planCounts.reduce((sum, p) => {
    return sum + (planPricing[p.subscriptionPlan ?? ''] ?? 0) * p._count
  }, 0)
  if (mrr >= 2500) return null
  return {
    checkType: 'MKT_MRR_BELOW_TARGET',
    severity: 'MEDIUM',
    message: `MRR is €${mrr.toLocaleString()} — Phase 1 target is €2,500+`,
    count: 1,
    details: { mrr, target: 2500 },
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: STAY REVIEWS (MANDATORY)
// ─────────────────────────────────────────────────────────────────

const review_pendingOverdue: CheckFn = async (now) => {
  const fortyEightHoursAgo = new Date(now.getTime() - 48 * 3600 * 1000)
  const overdue = await prisma.reservation.count({
    where: {
      status: 'COMPLETED',
      checkOut: { lt: fortyEightHoursAgo },
      stayReview: null,
    },
  })
  if (overdue === 0) return null
  return {
    checkType: 'REVIEW_PENDING_48H',
    severity: 'HIGH',
    message: `${overdue} checkout(s) without cleaning review for 48h+ — Manager must review`,
    count: overdue,
  }
}

const review_lowScoreTrend: CheckFn = async () => {
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 3600 * 1000)
  const recentReviews = await prisma.stayReview.findMany({
    where: { createdAt: { gte: thirtyDaysAgo } },
    select: { overallRating: true, crewMemberId: true },
  })
  if (recentReviews.length < 5) return null
  const avgRating = recentReviews.reduce((s, r) => s + Number(r.overallRating), 0) / recentReviews.length
  if (avgRating >= 3.5) return null
  return {
    checkType: 'REVIEW_LOW_AVG_30D',
    severity: 'CRITICAL',
    message: `Average cleaning review score is ${avgRating.toFixed(1)} in last 30 days — below 3.5 threshold`,
    count: recentReviews.length,
    details: { avgRating: avgRating.toFixed(2), reviewCount: recentReviews.length },
  }
}

export const ALL_CHECKS: CheckFn[] = [
  // Reservations (4)
  r1_overdueCheckins,
  r2_checkinsWithoutTask,
  r5_zeroAmountReservations,
  r_overlappingReservations,
  // Payouts & Invoices (6)
  p1_paidPayoutsNoInvoice,
  p1b_duplicateInvoices,
  p2_overduePayouts,
  p3_commissionMismatch,
  p4_invoicesNoPaidAt,
  p5_financialIntegrity,
  // Properties (3)
  prop_stale,
  prop_activeNoOwner,
  prop_activeNoPhotos,
  // Users (3)
  u_duplicateEmails,
  u_clientsWithoutManager,
  u_managerIdleClients,
  // Tasks (2)
  t_unassignedOverdue,
  t_72hUnassigned,
  // Tax (2)
  tax_overdue,
  tax_dueIn7Days,
  // CRM & Lead Pipeline (4)
  lead_staleContact,
  lead_convertedNoContract,
  lead_unattributedClients,
  lead_noFollowUp,
  // Crew Health (6)
  crew_scoreDrop,
  crew_suspended,
  crew_completionRate,
  crew_propertyRisk,
  crew_payoutStuck,
  crew_interventionsOpen,
  // Partner Program (3)
  partner_payoutOverdue,
  partner_reversalDeadline,
  partner_inactiveWithLeads,
  // Marketing Plan Health (5)
  mkt_lowLeadVolume,
  mkt_lowConversion,
  mkt_noPartnerReferrals,
  mkt_churnAlert,
  mkt_mrrTracking,
  // Stay Reviews — Mandatory (2)
  review_pendingOverdue,
  review_lowScoreTrend,
  // Stock / Consumables (2)
  stock_criticalLow,
  stock_laundryStuck,
]

// Total: 43 checks
