/**
 * AI Monitor — check definitions
 *
 * Each check returns a { checkType, severity, message, count, details? }
 * when an anomaly is detected, or null when everything is fine.
 *
 * Severity:
 *   CRITICAL — imediata acção, afecta dinheiro ou segurança
 *   HIGH     — requer acção do admin em <24h
 *   MEDIUM   — operacional, não-bloqueante
 *   LOW      — informativo, nice-to-have
 */
import { prisma } from '@/lib/prisma'
import { PLAN_COMMISSION } from '@/lib/finance'

export type CheckSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'

export type CheckResult = {
  checkType: string
  severity: CheckSeverity
  message: string
  count: number
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  details?: Record<string, any>
  canAutoFix?: boolean
}

export type CheckFn = (now: Date) => Promise<CheckResult | null>

// ─────────────────────────────────────────────────────────────────
// CATEGORY: RESERVATIONS
// ─────────────────────────────────────────────────────────────────

const r1_overdueCheckins: CheckFn = async (now) => {
  const count = await prisma.reservation.count({
    where: { status: 'UPCOMING', checkIn: { lt: now } },
  })
  if (count === 0) return null
  return {
    checkType: 'RESERVATION_PAST_CHECKIN',
    severity: 'HIGH',
    message: `${count} reserva(s) com estado UPCOMING mas check-in já passou`,
    count,
  }
}

const r2_checkinsWithoutTask: CheckFn = async (now) => {
  const in7Days = new Date(now.getTime() + 7 * 24 * 3600 * 1000)
  const upcomingCheckIns = await prisma.reservation.findMany({
    where: { checkIn: { gte: now, lte: in7Days }, status: { in: ['UPCOMING', 'ACTIVE'] } },
    select: { id: true, propertyId: true },
  })
  if (upcomingCheckIns.length === 0) return null
  const propIds = Array.from(new Set(upcomingCheckIns.map(r => r.propertyId)))
  const existingTasks = await prisma.task.findMany({
    where: { type: 'CHECK_IN', propertyId: { in: propIds }, dueDate: { gte: now, lte: in7Days }, status: { not: 'COMPLETED' } },
    select: { propertyId: true },
  })
  const covered = new Set(existingTasks.map(t => t.propertyId))
  const missing = upcomingCheckIns.filter(r => !covered.has(r.propertyId)).length
  if (missing === 0) return null
  return {
    checkType: 'CHECKIN_NO_TASK',
    severity: 'MEDIUM',
    message: `${missing} reserva(s) com check-in em <7 dias sem tarefa CHECK_IN`,
    count: missing,
  }
}

const r5_zeroAmountReservations: CheckFn = async () => {
  const count = await prisma.reservation.count({
    where: { amount: 0, status: { not: 'CANCELLED' } },
  })
  if (count === 0) return null
  return {
    checkType: 'RESERVATION_ZERO_AMOUNT',
    severity: 'MEDIUM',
    message: `${count} reserva(s) activa(s) com valor €0`,
    count,
  }
}

const r_overlappingReservations: CheckFn = async () => {
  // Find reservations that overlap on the same property (excluding CANCELLED)
  const overlaps = await prisma.$queryRaw<{ count: bigint }[]>`
    SELECT COUNT(*)::bigint AS count FROM (
      SELECT r1.id
      FROM "Reservation" r1
      JOIN "Reservation" r2 ON r1."propertyId" = r2."propertyId" AND r1.id < r2.id
      WHERE r1.status != 'CANCELLED' AND r2.status != 'CANCELLED'
        AND r1."checkIn" < r2."checkOut" AND r2."checkIn" < r1."checkOut"
    ) AS overlaps
  `
  const count = Number(overlaps[0]?.count ?? 0)
  if (count === 0) return null
  return {
    checkType: 'RESERVATION_OVERLAP',
    severity: 'CRITICAL',
    message: `${count} par(es) de reservas sobrepostas na mesma propriedade`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: PAYOUTS & INVOICES
// ─────────────────────────────────────────────────────────────────

const p1_paidPayoutsNoInvoice: CheckFn = async () => {
  const paidPayoutsCount = await prisma.payout.count({ where: { status: 'PAID' } })
  const autoInvoicesCount = await prisma.invoice.count({ where: { isAutoGenerated: true, status: 'PAID' } })
  const missing = Math.max(0, paidPayoutsCount - autoInvoicesCount)
  if (missing === 0) return null
  return {
    checkType: 'PAYOUT_NO_INVOICE',
    severity: 'HIGH',
    message: `${missing} payout(s) pago(s) sem invoice auto-gerado`,
    count: missing,
  }
}

const p1b_duplicateInvoices: CheckFn = async () => {
  const paidPayoutsCount = await prisma.payout.count({ where: { status: 'PAID' } })
  const autoInvoicesCount = await prisma.invoice.count({ where: { isAutoGenerated: true, status: 'PAID' } })
  const duplicates = Math.max(0, autoInvoicesCount - paidPayoutsCount)
  if (duplicates === 0) return null
  return {
    checkType: 'INVOICE_DUPLICATE',
    severity: 'CRITICAL',
    message: `${duplicates} invoice(s) auto-gerado(s) a mais que payouts pagos — possível duplicação`,
    count: duplicates,
  }
}

const p2_overduePayouts: CheckFn = async (now) => {
  const count = await prisma.payout.count({
    where: { status: 'SCHEDULED', scheduledFor: { lt: now } },
  })
  if (count === 0) return null
  return {
    checkType: 'PAYOUT_OVERDUE',
    severity: 'HIGH',
    message: `${count} payout(s) em atraso — data agendada já passou`,
    count,
  }
}

const p3_commissionMismatch: CheckFn = async () => {
  const scheduledPayouts = await prisma.payout.findMany({
    where: { status: 'SCHEDULED' },
    select: { id: true, commissionRate: true, property: { select: { owner: { select: { subscriptionPlan: true } } } } },
  })
  const mismatched = scheduledPayouts.filter(p => {
    const plan = p.property?.owner?.subscriptionPlan
    if (!plan) return false
    return Math.abs(p.commissionRate - (PLAN_COMMISSION[plan] ?? 0) * 100) > 0.1
  })
  if (mismatched.length === 0) return null
  return {
    checkType: 'COMMISSION_MISMATCH',
    severity: 'MEDIUM',
    message: `${mismatched.length} payout(s) com taxa diferente do plano actual do proprietário`,
    count: mismatched.length,
    details: { payoutIds: mismatched.map(p => p.id).slice(0, 50) },
    canAutoFix: true,
  }
}

const p4_invoicesNoPaidAt: CheckFn = async () => {
  const count = await prisma.invoice.count({ where: { status: 'PAID', paidAt: null } })
  if (count === 0) return null
  return {
    checkType: 'INVOICE_PAID_NO_PAIDAT',
    severity: 'HIGH',
    message: `${count} invoice(s) PAID sem data de pagamento — invisíveis no dashboard`,
    count,
    canAutoFix: true,
  }
}

const p5_financialIntegrity: CheckFn = async () => {
  // gross = commission + net should always hold. Find violations.
  const violations = await prisma.$queryRaw<{ count: bigint }[]>`
    SELECT COUNT(*)::bigint AS count FROM "Payout"
    WHERE ABS("grossAmount" - "commission" - "netAmount") > 0.01
  `
  const count = Number(violations[0]?.count ?? 0)
  if (count === 0) return null
  return {
    checkType: 'PAYOUT_MATH_MISMATCH',
    severity: 'CRITICAL',
    message: `${count} payout(s) com gross ≠ commission + net — erro aritmético`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: PROPERTIES
// ─────────────────────────────────────────────────────────────────

const prop_stale: CheckFn = async (now) => {
  const ninetyDaysAgo = new Date(now.getTime() - 90 * 24 * 3600 * 1000)
  const count = await prisma.property.count({
    where: { status: 'ACTIVE', reservations: { none: { checkIn: { gte: ninetyDaysAgo } } } },
  })
  if (count === 0) return null
  return {
    checkType: 'PROPERTY_STALE',
    severity: 'LOW',
    message: `${count} propriedade(s) activa(s) sem reservas há 90+ dias`,
    count,
  }
}

const prop_activeNoOwner: CheckFn = async () => {
  // ownerId is required in schema; check via raw query for safety / historical records
  const result = await prisma.$queryRaw<{ count: bigint }[]>`
    SELECT COUNT(*)::bigint AS count FROM "Property"
    WHERE status = 'ACTIVE' AND "ownerId" IS NULL
  `
  const count = Number(result[0]?.count ?? 0)
  if (count === 0) return null
  return {
    checkType: 'PROPERTY_ACTIVE_NO_OWNER',
    severity: 'CRITICAL',
    message: `${count} propriedade(s) ACTIVE sem proprietário — dados órfãos`,
    count,
  }
}

const prop_activeNoPhotos: CheckFn = async () => {
  const props = await prisma.property.findMany({
    where: { status: 'ACTIVE' },
    select: { id: true, photos: true },
  })
  const count = props.filter(p => !p.photos || p.photos.length === 0).length
  if (count === 0) return null
  return {
    checkType: 'PROPERTY_NO_PHOTOS',
    severity: 'MEDIUM',
    message: `${count} propriedade(s) ACTIVE sem fotos`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: USERS & ROLES
// ─────────────────────────────────────────────────────────────────

const u_duplicateEmails: CheckFn = async () => {
  // Schema makes email unique, but belt-and-braces check (case-insensitive dups):
  const dupes = await prisma.$queryRaw<{ email: string; n: bigint }[]>`
    SELECT LOWER(email) AS email, COUNT(*)::bigint AS n
    FROM "User"
    GROUP BY LOWER(email)
    HAVING COUNT(*) > 1
  `
  if (dupes.length === 0) return null
  return {
    checkType: 'USER_DUPLICATE_EMAIL',
    severity: 'HIGH',
    message: `${dupes.length} email(s) duplicado(s) (case-insensitive) no modelo User`,
    count: dupes.length,
    details: { examples: dupes.slice(0, 5) },
  }
}

const u_clientsWithoutManager: CheckFn = async () => {
  const count = await prisma.user.count({
    where: { role: 'CLIENT', managerId: null },
  })
  if (count === 0) return null
  return {
    checkType: 'CLIENT_NO_MANAGER',
    severity: 'MEDIUM',
    message: `${count} cliente(s) sem manager atribuído`,
    count,
  }
}

const u_managerIdleClients: CheckFn = async () => {
  // Manager with 0 clients
  const managers = await prisma.user.findMany({
    where: { role: 'MANAGER' },
    select: { id: true, _count: { select: { clients: true } } },
  })
  const idle = managers.filter(m => m._count.clients === 0).length
  if (idle === 0) return null
  return {
    checkType: 'MANAGER_NO_CLIENTS',
    severity: 'LOW',
    message: `${idle} manager(s) sem clientes atribuídos`,
    count: idle,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: TASKS
// ─────────────────────────────────────────────────────────────────

const t_unassignedOverdue: CheckFn = async (now) => {
  const count = await prisma.task.count({
    where: { status: { not: 'COMPLETED' }, assigneeId: null, dueDate: { lt: now } },
  })
  if (count === 0) return null
  return {
    checkType: 'TASK_UNASSIGNED_OVERDUE',
    severity: 'HIGH',
    message: `${count} tarefa(s) em atraso sem crew atribuído`,
    count,
  }
}

const t_72hUnassigned: CheckFn = async (now) => {
  const threeDaysAgo = new Date(now.getTime() - 72 * 3600 * 1000)
  const count = await prisma.task.count({
    where: { assigneeId: null, createdAt: { lt: threeDaysAgo }, status: { not: 'COMPLETED' } },
  })
  if (count === 0) return null
  return {
    checkType: 'TASK_72H_UNASSIGNED',
    severity: 'MEDIUM',
    message: `${count} tarefa(s) criadas há >72h sem crew atribuído`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: TAX OBLIGATIONS
// ─────────────────────────────────────────────────────────────────

const tax_overdue: CheckFn = async (now) => {
  const count = await prisma.taxObligation.count({
    where: {
      status: { in: ['NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED'] },
      dueDate: { lt: now },
    },
  })
  if (count === 0) return null
  return {
    checkType: 'TAX_OVERDUE',
    severity: 'HIGH',
    message: `${count} obrigação(ões) fiscal(is) com prazo ultrapassado`,
    count,
  }
}

const tax_dueIn7Days: CheckFn = async (now) => {
  const in7Days = new Date(now.getTime() + 7 * 24 * 3600 * 1000)
  const count = await prisma.taxObligation.count({
    where: {
      status: { in: ['NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED'] },
      dueDate: { gte: now, lte: in7Days },
    },
  })
  if (count === 0) return null
  return {
    checkType: 'TAX_DUE_SOON',
    severity: 'MEDIUM',
    message: `${count} obrigação(ões) fiscal(is) com prazo em <7 dias`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: CRM / LEADS
// ─────────────────────────────────────────────────────────────────

const lead_staleContact: CheckFn = async (now) => {
  const fourteenDaysAgo = new Date(now.getTime() - 14 * 24 * 3600 * 1000)
  const count = await prisma.lead.count({
    where: {
      status: { in: ['NEW', 'CONTACTED'] },
      createdAt: { lt: fourteenDaysAgo },
    },
  })
  if (count === 0) return null
  return {
    checkType: 'LEAD_STALE',
    severity: 'MEDIUM',
    message: `${count} lead(s) parado(s) há >14 dias sem progresso`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// CATEGORY: CREW HEALTH
// ─────────────────────────────────────────────────────────────────

const crew_scoreDrop: CheckFn = async () => {
  // Crew whose score dropped 50+ points in the last 30 days
  const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 3600 * 1000)
  const events = await prisma.crewScoreEvent.findMany({
    where: { createdAt: { gte: thirtyDaysAgo }, delta: { lt: 0 } },
    select: { crewScoreId: true, delta: true },
  })
  const dropByScore: Record<string, number> = {}
  for (const e of events) {
    dropByScore[e.crewScoreId] = (dropByScore[e.crewScoreId] ?? 0) + e.delta
  }
  const severe = Object.entries(dropByScore).filter(([, d]) => d <= -50)
  if (severe.length === 0) return null
  return {
    checkType: 'CREW_SCORE_DROP',
    severity: 'HIGH',
    message: `${severe.length} crew member(s) lost 50+ score points in the last 30 days`,
    count: severe.length,
    details: { crewScoreIds: severe.map(([id]) => id).slice(0, 20) },
  }
}

const crew_suspended: CheckFn = async () => {
  const count = await prisma.crewScore.count({ where: { level: 'SUSPENDED' } })
  if (count === 0) return null
  return {
    checkType: 'CREW_SUSPENDED',
    severity: 'HIGH',
    message: `${count} crew member(s) currently SUSPENDED (score <50) — cannot receive tasks`,
    count,
  }
}

const crew_completionRate: CheckFn = async () => {
  // Crew with totalTasks >= 5 but approval rate < 80%
  const scores = await prisma.crewScore.findMany({
    where: { totalTasks: { gte: 5 } },
    select: { userId: true, totalTasks: true, totalApproved: true, totalRejected: true },
  })
  const lowRate = scores.filter(s => s.totalTasks > 0 && (s.totalApproved / s.totalTasks) < 0.8)
  if (lowRate.length === 0) return null
  return {
    checkType: 'CREW_LOW_APPROVAL_RATE',
    severity: 'MEDIUM',
    message: `${lowRate.length} crew member(s) with <80% task approval rate (5+ tasks)`,
    count: lowRate.length,
    details: { userIds: lowRate.map(s => s.userId).slice(0, 20) },
  }
}

const crew_propertyRisk: CheckFn = async () => {
  // Active risk alerts on crew-property relationships
  const count = await prisma.crewPropertyRelationship.count({
    where: { aiAlertActive: true },
  })
  if (count === 0) return null
  return {
    checkType: 'CREW_PROPERTY_RISK',
    severity: 'HIGH',
    message: `${count} crew-property relationship(s) with active AI risk alert — substitution recommended`,
    count,
  }
}

const crew_payoutStuck: CheckFn = async (now) => {
  // CrewPayouts stuck in PENDING for more than 3 days
  const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 3600 * 1000)
  const count = await prisma.crewPayout.count({
    where: { status: 'PENDING', createdAt: { lt: threeDaysAgo } },
  })
  if (count === 0) return null
  return {
    checkType: 'CREW_PAYOUT_STUCK',
    severity: 'HIGH',
    message: `${count} crew payout(s) stuck in PENDING for 3+ days — crew not paid`,
    count,
  }
}

const crew_interventionsOpen: CheckFn = async (now) => {
  // Interventions open for more than 24h
  const oneDayAgo = new Date(now.getTime() - 24 * 3600 * 1000)
  const count = await prisma.crewIntervention.count({
    where: { status: 'OPEN', createdAt: { lt: oneDayAgo } },
  })
  if (count === 0) return null
  return {
    checkType: 'CREW_INTERVENTION_STALE',
    severity: 'MEDIUM',
    message: `${count} intervention(s) open for 24h+ without resolution`,
    count,
  }
}

// ─────────────────────────────────────────────────────────────────
// ALL CHECKS REGISTRY
// ─────────────────────────────────────────────────────────────────

export const ALL_CHECKS: CheckFn[] = [
  // Reservations (4)
  r1_overdueCheckins,
  r2_checkinsWithoutTask,
  r5_zeroAmountReservations,
  r_overlappingReservations,
  // Payouts & Invoices (6)
  p1_paidPayoutsNoInvoice,
  p1b_duplicateInvoices,
  p2_overduePayouts,
  p3_commissionMismatch,
  p4_invoicesNoPaidAt,
  p5_financialIntegrity,
  // Properties (3)
  prop_stale,
  prop_activeNoOwner,
  prop_activeNoPhotos,
  // Users (3)
  u_duplicateEmails,
  u_clientsWithoutManager,
  u_managerIdleClients,
  // Tasks (2)
  t_unassignedOverdue,
  t_72hUnassigned,
  // Tax (2)
  tax_overdue,
  tax_dueIn7Days,
  // CRM (1)
  lead_staleContact,
  // Crew Health (6)
  crew_scoreDrop,
  crew_suspended,
  crew_completionRate,
  crew_propertyRisk,
  crew_payoutStuck,
  crew_interventionsOpen,
]

// Total: 27 checks
