import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireRole } from '@/lib/session'
import { PLAN_COMMISSION } from '@/lib/finance'

export type MonitorResult = {
  type: string
  severity: 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO'
  message: string
  count: number
  action: { label: string; href: string }
}

export async function GET() {
  const guard = await requireRole(['ADMIN'])
  if (guard.error) return NextResponse.json({ error: guard.error }, { status: guard.status })

  const issues: MonitorResult[] = []
  const now = new Date()

  // ── 1. Invoices PAID sem paidAt (ficam invisíveis no dashboard) ──────────────
  const invoicesNoPaidAt = await prisma.invoice.count({
    where: { status: 'PAID', paidAt: null },
  })
  if (invoicesNoPaidAt > 0) {
    issues.push({
      type: 'INVOICE_PAID_NO_PAIDAT',
      severity: 'HIGH',
      message: `${invoicesNoPaidAt} invoice${invoicesNoPaidAt > 1 ? 's' : ''} marcado${invoicesNoPaidAt > 1 ? 's' : ''} como PAID sem data de pagamento — invisível no dashboard`,
      count: invoicesNoPaidAt,
      action: { label: 'Ver invoices', href: '/invoices' },
    })
  }

  // ── 2. Payouts PAID vs invoices auto-gerados (detecção de mismatch) ──────────
  const paidPayoutsCount = await prisma.payout.count({ where: { status: 'PAID' } })
  const autoInvoicesCount = await prisma.invoice.count({
    where: { isAutoGenerated: true, status: 'PAID' },
  })
  const missingInvoices = Math.max(0, paidPayoutsCount - autoInvoicesCount)
  if (missingInvoices > 0) {
    issues.push({
      type: 'PAYOUT_NO_INVOICE',
      severity: 'HIGH',
      message: `${missingInvoices} payout${missingInvoices > 1 ? 's' : ''} pago${missingInvoices > 1 ? 's' : ''} sem invoice auto-gerado correspondente`,
      count: missingInvoices,
      action: { label: 'Ver payouts', href: '/payouts' },
    })
  }

  // ── 3. Reservas próximas (<7 dias) sem tarefa CHECK_IN ────────────────────────
  const in7Days = new Date(now)
  in7Days.setDate(in7Days.getDate() + 7)

  const upcomingReservations = await prisma.reservation.findMany({
    where: {
      checkIn: { gte: now, lte: in7Days },
      status: { in: ['UPCOMING', 'ACTIVE'] },
    },
    select: { id: true, propertyId: true, guestName: true },
  })

  const reservationPropertyIds = Array.from(new Set(upcomingReservations.map(r => r.propertyId)))

  const checkinTasks = reservationPropertyIds.length > 0
    ? await prisma.task.findMany({
        where: {
          type: 'CHECK_IN',
          propertyId: { in: reservationPropertyIds },
          dueDate: { gte: now, lte: in7Days },
          status: { not: 'COMPLETED' },
        },
        select: { propertyId: true },
      })
    : []

  const propertiesWithTask = new Set(checkinTasks.map(t => t.propertyId))
  const missingCheckInTasks = upcomingReservations.filter(
    r => !propertiesWithTask.has(r.propertyId)
  ).length

  if (missingCheckInTasks > 0) {
    issues.push({
      type: 'CHECKIN_NO_TASK',
      severity: 'MEDIUM',
      message: `${missingCheckInTasks} reserva${missingCheckInTasks > 1 ? 's' : ''} nos próximos 7 dias sem tarefa CHECK_IN atribuída`,
      count: missingCheckInTasks,
      action: { label: 'Ver calendar', href: '/calendar' },
    })
  }

  // ── 4. Taxa de comissão desactualizada em payouts SCHEDULED ───────────────────
  const scheduledPayouts = await prisma.payout.findMany({
    where: { status: 'SCHEDULED' },
    select: {
      id: true,
      commissionRate: true,
      property: {
        select: { owner: { select: { subscriptionPlan: true } } },
      },
    },
  })

  const mismatchedRates = scheduledPayouts.filter(p => {
    const plan = p.property?.owner?.subscriptionPlan
    if (!plan) return false
    const expectedRate = (PLAN_COMMISSION[plan] ?? 0) * 100
    return Math.abs(p.commissionRate - expectedRate) > 0.1
  }).length

  if (mismatchedRates > 0) {
    issues.push({
      type: 'COMMISSION_MISMATCH',
      severity: 'MEDIUM',
      message: `${mismatchedRates} payout${mismatchedRates > 1 ? 's' : ''} agendado${mismatchedRates > 1 ? 's' : ''} com taxa de comissão diferente do plano actual do proprietário`,
      count: mismatchedRates,
      action: { label: 'Ver payouts', href: '/payouts' },
    })
  }

  // ── 5. Propriedades ACTIVE sem actividade há 90 dias ─────────────────────────
  const ninetyDaysAgo = new Date(now)
  ninetyDaysAgo.setDate(ninetyDaysAgo.getDate() - 90)

  const staleProperties = await prisma.property.count({
    where: {
      status: 'ACTIVE',
      reservations: { none: { checkIn: { gte: ninetyDaysAgo } } },
    },
  })

  if (staleProperties > 0) {
    issues.push({
      type: 'PROPERTY_STALE',
      severity: 'LOW',
      message: `${staleProperties} propriedade${staleProperties > 1 ? 's' : ''} activa${staleProperties > 1 ? 's' : ''} sem reservas nos últimos 90 dias`,
      count: staleProperties,
      action: { label: 'Ver propriedades', href: '/my-properties' },
    })
  }

  return NextResponse.json({ issues, checkedAt: now.toISOString() })
}
