import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireRole } from '@/lib/session'
import { sendEmail, ownerStatementEmail, receiptPaidEmail } from '@/lib/email'
import { normalizeEmailLocale, ownerStatementI18n, receiptPaidI18n } from '@/lib/email-i18n'
import { notify } from '@/lib/notifications'

const DASHBOARD_URL = process.env.NEXTAUTH_URL || 'https://hostmasters.es'

export async function PATCH(request: NextRequest, { params }: { params: { id: string } }) {
  const guard = await requireRole(['ADMIN'])
  if (guard.error) return NextResponse.json({ error: guard.error }, { status: guard.status })
  const me = guard.user!

  try {
    const body = await request.json()
    const { status, scheduledFor, platform, description, grossAmount, force } = body as {
      status?: 'SCHEDULED' | 'PAID' | 'CANCELLED'
      scheduledFor?: string
      platform?: string
      description?: string
      grossAmount?: number
      force?: boolean
    }

    // General edit (only SCHEDULED payouts)
    if (!status) {
      const existing = await prisma.payout.findUnique({ where: { id: params.id }, select: { status: true, commissionRate: true } })
      if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 })
      if (existing.status !== 'SCHEDULED') return NextResponse.json({ error: 'Only SCHEDULED payouts can be edited' }, { status: 400 })

      const editData: Record<string, unknown> = {}
      if (scheduledFor) editData.scheduledFor = new Date(scheduledFor)
      if (platform !== undefined) editData.platform = platform || null
      if (description !== undefined) editData.description = description || null
      if (grossAmount !== undefined && grossAmount > 0) {
        const rate = existing.commissionRate / 100
        const commission = +(grossAmount * rate).toFixed(2)
        editData.grossAmount = grossAmount
        editData.commission = commission
        editData.netAmount = +(grossAmount - commission).toFixed(2)
      }

      const updated = await prisma.payout.update({ where: { id: params.id }, data: editData })
      return NextResponse.json(updated)
    }

    // Validate state transitions
    const existing = await prisma.payout.findUnique({ where: { id: params.id }, select: { id: true, status: true } })
    if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 })

    if (status === 'PAID') {
      if (existing.status === 'PAID') return NextResponse.json({ error: 'Payout already paid' }, { status: 409 })
      if (existing.status === 'CANCELLED') return NextResponse.json({ error: 'Cannot pay a cancelled payout' }, { status: 400 })
    }

    if (status === 'CANCELLED') {
      if (existing.status === 'CANCELLED') return NextResponse.json({ error: 'Payout already cancelled' }, { status: 409 })
      if (existing.status === 'PAID' && force !== true) {
        return NextResponse.json(
          { error: 'Cannot cancel a PAID payout. Manual refund required. Pass force:true to confirm.' },
          { status: 400 }
        )
      }
    }

    const data: Record<string, unknown> = { status }
    if (status === 'PAID') data.paidAt = new Date()
    if (status === 'CANCELLED') data.cancelledAt = new Date()

    // Atomically check status + update + create receipt
    const { payout, receipt } = await prisma.$transaction(async (tx) => {
      // Re-check status inside transaction to prevent race conditions
      const fresh = await tx.payout.findUnique({ where: { id: params.id }, select: { status: true } })
      if (status === 'PAID' && fresh?.status === 'PAID') throw new Error('ALREADY_PAID')

      const payout = await tx.payout.update({
        where: { id: params.id },
        data,
        include: {
          property: {
            select: {
              name: true,
              owner: { select: { id: true, name: true, email: true, language: true } },
            },
          },
          reservation: {
            select: { guestName: true, checkIn: true, checkOut: true },
          },
        },
      })

      // Cancel auto-generated receipt when cancelling a PAID payout
      if (status === 'CANCELLED' && existing.status === 'PAID') {
        await tx.paymentReceipt.updateMany({
          where: {
            isAutoGenerated: true,
            status: 'PAID',
            notes: { contains: existing.id },
          },
          data: { status: 'CANCELLED' },
        })
      }

      let receipt = null
      if (status === 'PAID') {
        const owner = payout.property?.owner
        const paidAt = payout.paidAt ?? new Date()
        const checkInStr  = payout.reservation ? payout.reservation.checkIn.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : null
        const checkOutStr = payout.reservation ? payout.reservation.checkOut.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : null
        const description = payout.reservation
          ? `Rental income — ${payout.property.name} · ${payout.reservation.guestName} (${checkInStr}–${checkOutStr})`
          : (payout as unknown as { description?: string }).description ?? `Manual payout — ${payout.property.name}`

        if (owner?.id) {
          const { generateReceiptNumber, vatOnNet } = await import('@/lib/receipts')
          const vat = vatOnNet(payout.netAmount)
          receipt = await tx.paymentReceipt.create({
            data: {
              receiptNumber: await generateReceiptNumber(),
              type:            'RENTAL_COMMISSION',
              clientId:        owner.id,
              createdById:     me.id,
              propertyId:      payout.propertyId,
              reservationId:   payout.reservationId ?? undefined,
              description,
              grossAmount:     vat.net,
              netAmount:       vat.net,
              vatRate:         vat.rate,
              vatAmount:       vat.vat,
              totalAmount:     vat.total,
              currency: 'EUR',
              status:          'PAID',
              isAutoGenerated: true,
              paidAt,
              notes: `Auto-generated from payout ${payout.id}`,
            },
          })
        }
      }

      return { payout, receipt }
    })

    // Emails fire AFTER the transaction — not atomic with DB, but safe to retry.
    if (status === 'PAID') {
      const owner = payout.property?.owner
      const paidAt = payout.paidAt ?? new Date()
      const checkInStr  = payout.reservation ? payout.reservation.checkIn.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : null
      const checkOutStr = payout.reservation ? payout.reservation.checkOut.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' }) : null
      const description = payout.reservation
        ? `Rental income — ${payout.property.name} · ${payout.reservation.guestName} (${checkInStr}–${checkOutStr})`
        : (payout as unknown as { description?: string }).description ?? `Manual payout — ${payout.property.name}`

      if (owner?.email) {
        const ownerLocale = normalizeEmailLocale(owner.language)
        await sendEmail({
          to: owner.email,
          subject: ownerStatementI18n.subject(ownerLocale, payout.property.name),
          html: ownerStatementEmail({
            ownerName:      owner.name || owner.email,
            propertyName:   payout.property.name,
            payoutId:       payout.id,
            grossAmount:    payout.grossAmount,
            commission:     payout.commission,
            commissionRate: payout.commissionRate,
            netAmount:      payout.netAmount,
            currency:       'EUR',
            paidAt:         paidAt.toISOString(),
            guestName:      payout.reservation?.guestName ?? '—',
            checkIn:        payout.reservation?.checkIn.toISOString() ?? paidAt.toISOString(),
            checkOut:       payout.reservation?.checkOut.toISOString() ?? paidAt.toISOString(),
            platform:       payout.platform,
            dashboardUrl:   `${DASHBOARD_URL}/client/payouts`,
            locale:         ownerLocale,
          }),
        }).catch(e => console.error('Owner statement email error:', e))

        // Send receipt confirmation email
        if (receipt) {
          await sendEmail({
            to: owner.email,
            subject: receiptPaidI18n.subject(ownerLocale, payout.property.name),
            html: receiptPaidEmail({
              clientName:  owner.name || owner.email,
              invoiceId:   receipt.id,
              description,
              amount:      payout.netAmount,
              currency:    'EUR',
              paidAt:      paidAt.toISOString(),
              dashboardUrl: `${DASHBOARD_URL}/client/payouts`,
              locale:      ownerLocale,
            }),
          }).catch(e => console.error('Invoice email error:', e))
        }
      }
    }

    if (status === 'PAID' && payout.property?.owner?.id) {
      notify({
        userId: payout.property.owner.id,
        type: 'PAYOUT_COMPLETED',
        title: `Payout received: €${payout.netAmount.toFixed(0)}`,
        body: payout.property.name ?? 'Your property',
        link: '/client/financials',
      }).catch(() => {})
    }

    return NextResponse.json(payout)
  } catch (error) {
    if (error instanceof Error && error.message === 'ALREADY_PAID') {
      return NextResponse.json({ error: 'Payout already paid' }, { status: 409 })
    }
    console.error('Error updating payout:', error)
    return NextResponse.json({ error: 'Failed to update payout' }, { status: 500 })
  }
}

export async function DELETE(_request: NextRequest, { params }: { params: { id: string } }) {
  const guard = await requireRole(['ADMIN'])
  if (guard.error) return NextResponse.json({ error: guard.error }, { status: guard.status })

  try {
    const payout = await prisma.payout.findUnique({ where: { id: params.id }, select: { status: true } })
    if (!payout) return NextResponse.json({ error: 'Not found' }, { status: 404 })
    if (payout.status !== 'CANCELLED') return NextResponse.json({ error: 'Only cancelled payouts can be deleted' }, { status: 400 })

    await prisma.$transaction(async (tx) => {
      // Delete orphaned auto-generated receipts
      await tx.paymentReceipt.deleteMany({
        where: {
          isAutoGenerated: true,
          notes: { contains: params.id },
        },
      })
      await tx.payout.delete({ where: { id: params.id } })
    })
    return NextResponse.json({ ok: true })
  } catch (error) {
    console.error('Error deleting payout:', error)
    return NextResponse.json({ error: 'Failed to delete payout' }, { status: 500 })
  }
}
