"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import {
  CalendarDays, MessageCircle, FileText, Lock, Wifi, Wrench,
  CheckCircle2, TrendingUp, Phone, ArrowRight, Sparkles, ShieldCheck, AlertTriangle,
} from "lucide-react"
import { PlanBadge } from "@/components/hm/plan-badge"
import { DashboardGreeting } from "@/components/hm/dashboard-entrance"
import { StarterDashboard } from "@/components/hm/starter-dashboard"
import { useLocale } from "@/i18n/provider"

type DashboardData = {
  property: {
    id: string
    name: string
    address: string
    city: string
    plan: string
    status: string
    airbnbUrl?: string
    bookingUrl?: string
    lastCleaningAt?: string
    lastInspectionAt?: string
    smartLockId?: string
  } | null
  earnings: {
    thisMonth: number
    occupancyPct: number
  }
  nextBooking: {
    guestName: string
    guestNationality?: string
    checkIn: string
    checkOut: string
  } | null
  recentVisits: {
    id: string
    title: string
    type: string
    dueDate: string
    propertyName: string
    flagged: boolean
  }[]
  upcomingVisits: number
  flaggedIssues: number
  manager?: {
    name: string
    phone?: string
  }
}

const fmtEUR = (n: number) =>
  new Intl.NumberFormat("en-IE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(n)

const fmtDate = (s: string) =>
  new Date(s).toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })

const FLAGS: Record<string, string> = {
  GB:"🇬🇧", SE:"🇸🇪", NO:"🇳🇴", DK:"🇩🇰",
  NL:"🇳🇱", DE:"🇩🇪", FR:"🇫🇷", ES:"🇪🇸", IT:"🇮🇹",
}

export default function OwnerDashboard() {
  const [data, setData] = useState<DashboardData | null>(null)
  const [loading, setLoading] = useState(true)
  const [isStarter, setIsStarter] = useState<boolean | null>(null)
  const [userName, setUserName] = useState<string>('')

  const { t } = useLocale()
  const [pendingInvoices, setPendingInvoices] = useState<{ count: number; total: number }>({ count: 0, total: 0 })
  const [hasContractPending, setHasContractPending] = useState(false)
  const [fetchErrors, setFetchErrors] = useState<string[]>([])

  // Detect plan early — drives whether we show StarterDashboard or full
  useEffect(() => {
    fetch('/api/me')
      .then(r => r.ok ? r.json() : null)
      .then(d => {
        setIsStarter(!d?.subscriptionPlan || d.subscriptionPlan === 'STARTER')
        const first = d?.name?.split(' ')[0]
        const emailFallback = d?.email?.split('@')[0]
        setUserName(first || emailFallback || '')
      })
      .catch(() => setIsStarter(false))
  }, [])

  useEffect(() => {
    type Payout = { scheduledFor: string; status: string; netAmount: number }
    type Reservation = {
      status: string
      guestName: string
      guestNationality?: string
      checkIn: string
      checkOut: string
      nights?: number
    }
    type Invoice = { status: string; isAutoGenerated?: boolean; amount: number }
    type Task = {
      id: string
      title: string
      type: string
      dueDate: string
      status: string
      notes?: string
      property?: { name: string }
    }

    async function load() {
      try {
        const [propRes, payRes, resRes, taskRes, invRes] = await Promise.all([
          fetch("/api/properties"),
          fetch("/api/payouts"),
          fetch("/api/reservations"),
          fetch("/api/tasks"),
          fetch("/api/invoices"),
        ])

        const errors: string[] = []
        if (!propRes.ok) errors.push(t('client.dashboard.errorProperties'))
        if (!payRes.ok) errors.push(t('client.dashboard.errorPayouts'))
        if (!resRes.ok) errors.push(t('client.dashboard.errorReservations'))
        if (!taskRes.ok) errors.push(t('client.dashboard.errorTasks'))
        if (!invRes.ok) errors.push(t('client.dashboard.errorInvoices'))
        setFetchErrors(errors)

        const properties = propRes.ok ? await propRes.json() : []
        const payouts: Payout[] = payRes.ok ? await payRes.json() : []
        const reservations: Reservation[] = resRes.ok ? await resRes.json() : []
        const allTasks: Task[] = taskRes.ok ? await taskRes.json() : []
        const invoices: Invoice[] = invRes.ok ? await invRes.json() : []

        // Pending invoices (DRAFT or SENT, not auto-generated)
        const pending = invoices.filter((i: Invoice) => (i.status === 'SENT' || i.status === 'DRAFT') && !i.isAutoGenerated)
        setPendingInvoices({
          count: pending.length,
          total: pending.reduce((s: number, i: Invoice) => s + i.amount, 0),
        })

        // Check for any property with CONTRACT_PENDING status
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        setHasContractPending(properties.some((p: any) => p.status === 'CONTRACT_PENDING'))

        const property = properties[0] ?? null
        const now = new Date()
        const monthStart = new Date(now.getFullYear(), now.getMonth(), 1)

        const monthPayouts = payouts.filter((p: Payout) =>
          new Date(p.scheduledFor) >= monthStart && p.status !== "CANCELLED"
        )
        const thisMonth = monthPayouts.reduce((s: number, p: Payout) => s + p.netAmount, 0)

        const upcoming = reservations
          .filter((r: Reservation) => r.status === "UPCOMING" || r.status === "ACTIVE")
          .sort((a: Reservation, b: Reservation) => new Date(a.checkIn).getTime() - new Date(b.checkIn).getTime())
        const nextBooking = upcoming[0]
          ? {
              guestName: upcoming[0].guestName,
              guestNationality: upcoming[0].guestNationality,
              checkIn: upcoming[0].checkIn,
              checkOut: upcoming[0].checkOut,
            }
          : null

        // Occupancy: booked nights / days in month
        const daysInMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()
        const bookedNights = reservations
          .filter((r: Reservation) => r.status !== "CANCELLED")
          .reduce((s: number, r: Reservation) => s + (r.nights ?? 0), 0)
        const occupancyPct = Math.min(Math.round((bookedNights / daysInMonth) * 100), 100)

        // Task summary for the care section
        const upcomingVisits = allTasks.filter((t: Task) => t.status !== "COMPLETED").length
        const recentVisits = allTasks
          .filter((t: Task) => t.status === "COMPLETED")
          .sort((a: Task, b: Task) => new Date(b.dueDate).getTime() - new Date(a.dueDate).getTime())
          .slice(0, 3)
          .map((t: Task) => {
            let flagged = false
            try {
              if (t.notes) {
                const parsed = JSON.parse(t.notes)
                if (parsed?.condition === "minor" || parsed?.condition === "major") flagged = true
              }
            } catch { /* not a report */ }
            return {
              id: t.id,
              title: t.title,
              type: t.type,
              dueDate: t.dueDate,
              propertyName: t.property?.name ?? "",
              flagged,
            }
          })
        const flaggedIssues = recentVisits.filter((v: { flagged: boolean }) => v.flagged).length

        setData({
          property: property
            ? {
                id: property.id,
                name: property.name,
                address: property.address,
                city: property.city,
                plan: property.owner?.subscriptionPlan ?? "STARTER",
                status: property.status,
                airbnbUrl: property.airbnbIcalUrl,
                lastInspectionAt: property.lastInspectionAt,
                smartLockId: property.smartLockId,
              }
            : null,
          earnings: { thisMonth, occupancyPct },
          nextBooking,
          recentVisits,
          upcomingVisits,
          flaggedIssues,
          manager: undefined,
        })
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [])

  // Starter plan: short-circuit BEFORE loading check.
  // Starters don't need property/reservation data — they see services + upsell.
  if (isStarter) {
    return (
      <div className="space-y-6">
        {userName && (
          <DashboardGreeting
            nameOverride={userName}
            headingClass="text-3xl sm:text-4xl font-serif font-bold text-hm-black"
            dateClass="mt-1 font-sans text-hm-slate/70 text-base"
          />
        )}
        <StarterDashboard />
      </div>
    )
  }

  if (loading || isStarter === null) {
    return (
      <div className="space-y-6">
        {userName ? (
          <DashboardGreeting
            nameOverride={userName}
            headingClass="text-3xl sm:text-4xl font-serif font-bold text-hm-black"
            dateClass="mt-1 font-sans text-hm-slate/70 text-base"
          />
        ) : (
          <div>
            <div className="h-10 w-64 rounded-lg bg-gray-100 animate-pulse" />
            <div className="h-4 w-48 rounded-lg bg-gray-100 animate-pulse mt-2" />
          </div>
        )}
        <div className="space-y-6 animate-pulse">
          <div className="h-64 rounded-hm bg-hm-sand" />
          <div className="grid grid-cols-3 gap-4">
            <div className="h-28 rounded-hm bg-hm-sand" />
            <div className="h-28 rounded-hm bg-hm-sand" />
            <div className="h-28 rounded-hm bg-hm-sand" />
          </div>
        </div>
      </div>
    )
  }

  const prop = data?.property

  return (
    <div className="space-y-8">
      {/* Welcome */}
      <DashboardGreeting
        headingClass="text-3xl sm:text-4xl font-serif font-bold text-hm-black"
        dateClass="mt-1 font-sans text-hm-slate/70 text-base"
      />

      {/* Partial fetch errors banner */}
      {fetchErrors.length > 0 && (
        <div className="rounded-hm border border-yellow-300 bg-yellow-50 px-5 py-4">
          <div className="flex items-center gap-2 mb-1">
            <AlertTriangle className="h-4 w-4 text-yellow-600 shrink-0" />
            <p className="text-sm font-semibold text-yellow-800">{t('client.dashboard.partialLoadError')}</p>
          </div>
          <ul className="list-disc list-inside text-xs text-yellow-700 space-y-0.5">
            {fetchErrors.map((err, i) => <li key={i}>{err}</li>)}
          </ul>
        </div>
      )}

      {/* Contract pending alert */}
      {hasContractPending && (
        <Link href="/client/properties"
          className="flex items-center gap-3 rounded-hm border-2 border-blue-300 bg-blue-50 px-5 py-4 hover:bg-blue-100 transition-colors hm-animate-in hm-stagger-1">
          <FileText className="h-5 w-5 text-blue-600 shrink-0" />
          <div className="flex-1">
            <p className="text-sm font-semibold text-blue-800">
              {t('client.dashboard.pendingContract')}
            </p>
            <p className="text-xs text-blue-600 mt-0.5">
              {t('client.dashboard.pendingContractDesc')}
            </p>
          </div>
          <ArrowRight className="h-4 w-4 text-blue-400" />
        </Link>
      )}

      {/* Pending invoices alert */}
      {pendingInvoices.count > 0 && (
        <Link href="/client/payouts"
          className="flex items-center gap-3 rounded-hm border-2 border-orange-200 bg-orange-50 px-5 py-4 hover:bg-orange-100 transition-colors hm-animate-in hm-stagger-2">
          <AlertTriangle className="h-5 w-5 text-orange-500 shrink-0" />
          <div className="flex-1">
            <p className="text-sm font-semibold text-orange-800">
              {t('client.dashboard.pendingInvoice').replace('{n}', String(pendingInvoices.count))}
            </p>
            <p className="text-xs text-orange-600 mt-0.5">
              {t('client.dashboard.pendingInvoiceTotal').replace('{amount}', fmtEUR(pendingInvoices.total))}
            </p>
          </div>
          <ArrowRight className="h-4 w-4 text-orange-400" />
        </Link>
      )}

      {prop ? (
        <>
          {/* Property hero card */}
          <div data-tour="earnings-hero" className="rounded-hm border border-hm-border overflow-hidden hm-animate-in hm-stagger-2"
               style={{ background: 'var(--hm-sand)' }}>
            {/* Top bar with plan */}
            <div className="px-6 py-4 border-b border-hm-border flex items-center justify-between">
              <div>
                <h2 className="text-xl font-serif font-bold text-hm-black">{prop.name}</h2>
                <p className="font-sans text-sm text-hm-slate/70 mt-0.5">{prop.address}, {prop.city}</p>
              </div>
              <PlanBadge plan={prop.plan} size="md" />
            </div>

            {/* Earnings hero */}
            <div className="px-6 py-8 text-center border-b border-hm-border"
                 style={{ background: 'var(--hm-ivory)' }}>
              <p className="font-sans text-sm uppercase tracking-widest text-hm-slate/60 mb-2">
                {t('client.dashboard.earningsThisMonth')}
              </p>
              <p className="text-6xl font-serif font-bold text-hm-black">
                {fmtEUR(data?.earnings.thisMonth ?? 0)}
              </p>
              {/* Occupancy bar */}
              <div className="mt-4 max-w-xs mx-auto">
                <div className="flex items-center justify-between text-sm font-sans text-hm-slate/60 mb-1">
                  <span>{t('client.dashboard.occupancy')}</span>
                  <span className="font-semibold text-hm-black">{data?.earnings.occupancyPct ?? 0}%</span>
                </div>
                <div className="h-2 rounded-full overflow-hidden" style={{ background: 'var(--hm-border)' }}>
                  <div
                    className="h-full rounded-full transition-all"
                    style={{
                      width: `${data?.earnings.occupancyPct ?? 0}%`,
                      background: 'var(--hm-gold)',
                    }}
                  />
                </div>
              </div>
            </div>

            {/* Next booking + condition */}
            <div className="px-6 py-5 grid grid-cols-1 sm:grid-cols-2 gap-6">
              <div data-tour="next-guest">
                <p className="font-sans text-xs uppercase tracking-widest text-hm-slate/60 mb-2">
                  {t('client.dashboard.nextGuest')}
                </p>
                {data?.nextBooking ? (
                  <div className="flex items-center gap-2">
                    <span className="text-2xl">
                      {FLAGS[data.nextBooking.guestNationality ?? ""] ?? "🌍"}
                    </span>
                    <div>
                      <p className="font-serif font-semibold text-hm-black">
                        {data.nextBooking.guestName}
                      </p>
                      <p className="font-sans text-sm text-hm-slate/70">
                        {fmtDate(data.nextBooking.checkIn)} →{" "}
                        {new Date(data.nextBooking.checkOut).toLocaleDateString("en-GB", { day: "2-digit", month: "long" })}
                      </p>
                    </div>
                  </div>
                ) : (
                  <p className="font-sans text-hm-slate/60">{t('client.dashboard.noUpcoming')}</p>
                )}
              </div>

              <div data-tour="property-condition">
                <p className="font-sans text-xs uppercase tracking-widest text-hm-slate/60 mb-2">
                  {t('client.dashboard.propertyCondition')}
                </p>
                {(data?.flaggedIssues ?? 0) > 0 ? (
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="h-5 w-5 text-hm-red" />
                    <span className="font-serif font-semibold text-hm-red">
                      {t('client.dashboard.issuesFlagged').replace('{n}', String(data?.flaggedIssues ?? 0))}
                    </span>
                  </div>
                ) : (
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="h-5 w-5 text-hm-green" />
                    <span className="font-serif font-semibold text-hm-green">{t('client.dashboard.allGood')}</span>
                  </div>
                )}
                {prop.lastInspectionAt && (
                  <p className="font-sans text-sm text-hm-slate/60 mt-1">
                    {t('client.dashboard.lastInspected').replace('{date}', fmtDate(prop.lastInspectionAt))}
                  </p>
                )}
              </div>
            </div>
          </div>

          {/* Care snapshot */}
          <div data-tour="care-section" className="rounded-hm border border-hm-border overflow-hidden hm-animate-in hm-stagger-3"
               style={{ background: 'var(--hm-sand)' }}>
            <div className="px-6 py-4 border-b border-hm-border flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Wrench className="h-5 w-5 text-hm-gold-dk" />
                <h2 className="font-serif font-bold text-hm-black text-lg">{t('client.dashboard.careTitle')}</h2>
              </div>
              <Link
                href="/client/care"
                className="inline-flex items-center gap-1 font-sans text-sm text-hm-gold-dk hover:opacity-80"
              >
                {t('client.dashboard.seeAll')} <ArrowRight className="h-3.5 w-3.5" />
              </Link>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 divide-y sm:divide-y-0 sm:divide-x divide-hm-border">
              <div className="px-6 py-4">
                <p className="font-sans text-xs uppercase tracking-widest text-hm-slate/60 mb-1">
                  {t('client.dashboard.upcomingVisits')}
                </p>
                <p className="font-serif text-2xl font-bold text-hm-black">{data?.upcomingVisits ?? 0}</p>
              </div>
              <div className="px-6 py-4">
                <p className="font-sans text-xs uppercase tracking-widest text-hm-slate/60 mb-1">
                  {t('client.dashboard.openIssues')}
                </p>
                <p className={`font-serif text-2xl font-bold ${(data?.flaggedIssues ?? 0) > 0 ? "text-hm-red" : "text-hm-black"}`}>
                  {data?.flaggedIssues ?? 0}
                </p>
              </div>
            </div>
            {(data?.recentVisits?.length ?? 0) > 0 && (
              <div className="border-t border-hm-border divide-y divide-hm-border">
                {data?.recentVisits.map(v => {
                  const Icon = v.type === "CLEANING" ? Sparkles
                    : v.type === "MAINTENANCE_CORRECTIVE" ? Wrench
                    : ShieldCheck
                  return (
                    <div key={v.id} className="px-6 py-3 flex items-center gap-3">
                      <Icon className={`h-4 w-4 shrink-0 ${v.flagged ? "text-hm-red" : "text-hm-green"}`} />
                      <div className="flex-1 min-w-0">
                        <p className="font-sans text-sm font-semibold text-hm-black truncate">{v.title}</p>
                        <p className="font-sans text-xs text-hm-slate/60">{v.propertyName}</p>
                      </div>
                      <span className="font-sans text-xs text-hm-slate/60 shrink-0">{fmtDate(v.dueDate)}</span>
                    </div>
                  )
                })}
              </div>
            )}
          </div>

          {/* Quick actions */}
          <div data-tour="quick-actions" className="hm-animate-in hm-stagger-4">
            <h2 className="text-xl font-serif font-bold text-hm-black mb-4">{t('client.dashboard.quickActions')}</h2>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <Link
                href="/client/bookings"
                className="flex items-center gap-4 rounded-hm border border-hm-border p-5 hover:border-hm-gold/50 hover:shadow-sm transition-all"
                style={{ background: 'var(--hm-sand)' }}
              >
                <div className="h-12 w-12 rounded-full flex items-center justify-center"
                     style={{ background: 'var(--hm-gold)', opacity: 0.9 }}>
                  <CalendarDays className="h-6 w-6 text-white" />
                </div>
                <div>
                  <p className="font-serif font-bold text-hm-black">{t('client.dashboard.blockDates')}</p>
                  <p className="font-sans text-sm text-hm-slate/70">{t('client.dashboard.blockDatesDesc')}</p>
                </div>
              </Link>

              <Link
                href="/client/care"
                className="flex items-center gap-4 rounded-hm border border-hm-border p-5 hover:border-hm-gold/50 hover:shadow-sm transition-all"
                style={{ background: 'var(--hm-sand)' }}
              >
                <div className="h-12 w-12 rounded-full flex items-center justify-center"
                     style={{ background: 'var(--hm-green)' }}>
                  <Wrench className="h-6 w-6 text-white" />
                </div>
                <div>
                  <p className="font-serif font-bold text-hm-black">{t('client.dashboard.requestVisit')}</p>
                  <p className="font-sans text-sm text-hm-slate/70">{t('client.dashboard.requestVisitDesc')}</p>
                </div>
              </Link>

              <Link
                href="/client/financials"
                className="flex items-center gap-4 rounded-hm border border-hm-border p-5 hover:border-hm-gold/50 hover:shadow-sm transition-all"
                style={{ background: 'var(--hm-sand)' }}
              >
                <div className="h-12 w-12 rounded-full flex items-center justify-center"
                     style={{ background: 'var(--hm-blue)' }}>
                  <FileText className="h-6 w-6 text-white" />
                </div>
                <div>
                  <p className="font-serif font-bold text-hm-black">{t('client.dashboard.viewEarnings')}</p>
                  <p className="font-sans text-sm text-hm-slate/70">{t('client.dashboard.viewEarningsDesc')}</p>
                </div>
              </Link>
            </div>
          </div>

          {/* Status cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 hm-animate-in hm-stagger-5">
            {prop.smartLockId && (
              <div className="rounded-hm border border-hm-border p-5"
                   style={{ background: 'var(--hm-sand)' }}>
                <div className="flex items-center gap-3 mb-2">
                  <Lock className="h-5 w-5 text-hm-green" />
                  <span className="font-serif font-semibold text-hm-black">{t('client.dashboard.smartLock')}</span>
                </div>
                <p className="font-sans text-sm text-hm-slate/70">
                  {t('client.dashboard.smartLockActive').replace('{id}', prop.smartLockId)}
                </p>
                <div className="flex items-center gap-1.5 mt-2">
                  <span className="h-2 w-2 rounded-full bg-hm-green inline-block" />
                  <span className="font-sans text-sm text-hm-green">{t('client.dashboard.smartLockConnected')}</span>
                </div>
              </div>
            )}

            <div className="rounded-hm border border-hm-border p-5"
                 style={{ background: 'var(--hm-sand)' }}>
              <div className="flex items-center gap-3 mb-2">
                <TrendingUp className="h-5 w-5 text-hm-blue" />
                <span className="font-serif font-semibold text-hm-black">{t('client.dashboard.activeListings')}</span>
              </div>
              <div className="font-sans text-sm text-hm-slate/70 space-y-1">
                <p>✓ Airbnb</p>
                <p>✓ Booking.com</p>
                <p>✓ VRBO</p>
              </div>
            </div>
          </div>
        </>
      ) : (
        /* No property yet */
        <div className="rounded-hm border border-hm-border p-10 text-center"
             style={{ background: 'var(--hm-sand)' }}>
          <div className="h-16 w-16 rounded-full mx-auto mb-4 flex items-center justify-center"
               style={{ background: 'var(--hm-gold)', opacity: 0.8 }}>
            <Phone className="h-8 w-8 text-white" />
          </div>
          <h2 className="text-2xl font-serif font-bold text-hm-black mb-2">
            {t('client.dashboard.propertySetup')}
          </h2>
          <p className="font-sans text-hm-slate/70 max-w-md mx-auto">
            {t('client.dashboard.propertySetupDesc')}
          </p>
          <Link
            href="/client/messages"
            className="mt-6 inline-flex items-center gap-2 rounded-lg px-6 py-3 font-sans font-semibold text-white transition-opacity hover:opacity-90"
            style={{ background: 'var(--hm-black)' }}
          >
            <MessageCircle className="h-5 w-5" />
            {t('client.dashboard.contactManager')}
          </Link>
        </div>
      )}
    </div>
  )
}
