import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireRole } from '@/lib/session'
import { sendEmail, receiptCreatedEmail, receiptPaidEmail } from '@/lib/email'

const DASHBOARD_URL = process.env.NEXTAUTH_URL || 'https://hostmasters.es'

export async function PATCH(req: NextRequest, { params }: { params: { id: string } }) {
  const guard = await requireRole(['ADMIN', 'MANAGER'])
  if (guard.error) return NextResponse.json({ error: guard.error }, { status: guard.status })
  const me = guard.user!
  try {
    let status: 'DRAFT' | 'PENDING' | 'PAID' | 'CANCELLED' | undefined
    try {
      const body = await req.json() as { status?: 'DRAFT' | 'PENDING' | 'PAID' | 'CANCELLED' }
      status = body.status
    } catch {
      return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
    }
    if (!status) return NextResponse.json({ error: 'status required' }, { status: 400 })

    const VALID_STATUSES = ['DRAFT', 'PENDING', 'PAID', 'CANCELLED']
    if (!VALID_STATUSES.includes(status)) {
      return NextResponse.json({ error: 'invalid status' }, { status: 400 })
    }

    // Load existing invoice for ownership check and transition validation
    const existing = await prisma.paymentReceipt.findUnique({
      where: { id: params.id },
      select: { id: true, status: true, createdById: true, isAutoGenerated: true },
    })
    if (!existing) return NextResponse.json({ error: 'Invoice not found' }, { status: 404 })

    // Managers can only modify invoices they created
    if (me.role === 'MANAGER' && existing.createdById !== me.id) {
      return NextResponse.json({ error: 'forbidden' }, { status: 403 })
    }

    // Validate state transitions: DRAFT->SENT->PAID, any->CANCELLED; no backward from PAID/CANCELLED
    const ALLOWED_TRANSITIONS: Record<string, string[]> = {
      DRAFT: ['PENDING', 'CANCELLED'],
      SENT: ['PAID', 'CANCELLED'],
      PAID: ['CANCELLED'],
      CANCELLED: [],
    }
    if (!ALLOWED_TRANSITIONS[existing.status]?.includes(status)) {
      return NextResponse.json(
        { error: `Cannot transition from ${existing.status} to ${status}` },
        { status: 400 },
      )
    }

    const data: Record<string, unknown> = { status }
    if (status === 'PAID') data.paidAt = new Date()

    const invoice = await prisma.paymentReceipt.update({
      where: { id: params.id },
      data,
      include: { client: { select: { name: true, email: true } } },
    })

    // Send thank-you email when marked paid
    if (status === 'PAID' && invoice.client?.email) {
      try {
        await sendEmail({
          to: invoice.client.email,
          subject: `Payment confirmed — HostMasters`,
          html: receiptPaidEmail({
            clientName: invoice.client.name || invoice.client.email,
            invoiceId: invoice.id,
            description: invoice.description,
            amount: Number(invoice.totalAmount),
            currency: invoice.currency,
            paidAt: invoice.paidAt?.toISOString(),
            dashboardUrl: `${DASHBOARD_URL}/client/payouts`,
          }),
        })
      } catch (e) {
        console.error('Invoice paid email failed:', e)
        // Don't fail the request — invoice is saved, email can be retried
      }
    }

    return NextResponse.json(invoice)
  } catch (e) {
    console.error(e)
    return NextResponse.json({ error: 'Failed' }, { status: 500 })
  }
}

export async function PUT(req: NextRequest, { params }: { params: { id: string } }) {
  const guard = await requireRole(['ADMIN', 'MANAGER'])
  if (guard.error) return NextResponse.json({ error: guard.error }, { status: guard.status })
  const me = guard.user!
  try {
    let description, amount, dueDate, notes, propertyId
    try {
      const body = await req.json()
      ;({ description, amount, dueDate, notes, propertyId } = body)
    } catch {
      return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
    }
    if (!description || amount == null) {
      return NextResponse.json({ error: 'description and amount required' }, { status: 400 })
    }

    // Load existing invoice for ownership + state checks
    const existing = await prisma.paymentReceipt.findUnique({
      where: { id: params.id },
      select: { id: true, status: true, createdById: true, isAutoGenerated: true },
    })
    if (!existing) return NextResponse.json({ error: 'Invoice not found' }, { status: 404 })

    // Cannot edit PAID or CANCELLED invoices
    if (existing.status === 'PAID' || existing.status === 'CANCELLED') {
      return NextResponse.json({ error: `Cannot edit a ${existing.status} invoice` }, { status: 400 })
    }
    // Cannot edit auto-generated invoices (they're created by the payout flow)
    if (existing.isAutoGenerated) {
      return NextResponse.json({ error: 'Cannot edit auto-generated invoices' }, { status: 400 })
    }

    // Managers can only edit invoices they created
    if (me.role === 'MANAGER' && existing.createdById !== me.id) {
      return NextResponse.json({ error: 'forbidden' }, { status: 403 })
    }

    const invoice = await prisma.paymentReceipt.update({
      where: { id: params.id },
      data: {
        description,
        grossAmount: Number(amount),
        totalAmount: Number(amount),
        netAmount: Number(amount),
        dueDate: dueDate ? new Date(dueDate) : null,
        notes: notes || null,
        propertyId: propertyId || null,
      },
      include: { client: { select: { id: true, name: true, email: true } } },
    })
    return NextResponse.json(invoice)
  } catch (e) {
    console.error(e)
    return NextResponse.json({ error: 'Failed to update invoice' }, { status: 500 })
  }
}

export async function DELETE(req: NextRequest, { params }: { params: { id: string } }) {
  const guard = await requireRole(['ADMIN', 'MANAGER'])
  if (guard.error) return NextResponse.json({ error: guard.error }, { status: guard.status })
  const me = guard.user!
  try {
    const existing = await prisma.paymentReceipt.findUnique({
      where: { id: params.id },
      select: { id: true, status: true, createdById: true, isAutoGenerated: true },
    })
    if (!existing) return NextResponse.json({ error: 'Invoice not found' }, { status: 404 })

    // Cannot delete PAID invoices (audit trail)
    if (existing.status === 'PAID') {
      return NextResponse.json({ error: 'Cannot delete a PAID invoice' }, { status: 400 })
    }
    // Cannot delete auto-generated invoices directly (cancel the payout instead)
    if (existing.isAutoGenerated) {
      return NextResponse.json({ error: 'Cannot delete auto-generated invoices — cancel the payout instead' }, { status: 400 })
    }
    // Managers can only delete invoices they created
    if (me.role === 'MANAGER' && existing.createdById !== me.id) {
      return NextResponse.json({ error: 'forbidden' }, { status: 403 })
    }
    await prisma.paymentReceipt.delete({ where: { id: params.id } })
    return new NextResponse(null, { status: 204 })
  } catch (e) {
    console.error(e)
    return NextResponse.json({ error: 'Failed to delete invoice' }, { status: 500 })
  }
}
