-- Notification system

CREATE TYPE "NotificationType" AS ENUM (
  'TASK_ASSIGNED', 'TASK_CONFIRMED', 'TASK_SUBMITTED', 'TASK_APPROVED',
  'TASK_REJECTED', 'TASK_REDISTRIBUTED',
  'CREW_PAYOUT_READY', 'CREW_PAYOUT_PAID', 'CREW_SCORE_CHANGE',
  'CREW_LEVEL_UP', 'CREW_LEVEL_DOWN',
  'NEW_LEAD', 'CLIENT_REGISTERED', 'CLIENT_PROPERTY_APPROVED', 'COMMISSION_PAID',
  'PROPERTY_APPROVED', 'CONTRACT_READY', 'PROPERTY_ACTIVE',
  'BOOKING_RECEIVED', 'PAYOUT_COMPLETED', 'VISIT_COMPLETED', 'TAX_DEADLINE',
  'INTERVENTION_OPENED', 'INTERVENTION_RESOLVED',
  'AI_ALERT', 'GENERAL'
);

CREATE TABLE "Notification" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL DEFAULT 'GENERAL',
    "title" TEXT NOT NULL,
    "body" TEXT,
    "link" TEXT,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "readAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Notification_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "Notification_userId_read_createdAt_idx" ON "Notification"("userId", "read", "createdAt");

ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey"
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
