-- Invoice → PaymentReceipt refactor
-- Legal compliance: HostMasters generates payment receipts (recibos), NOT fiscal invoices.
-- Fiscal invoices are generated by Taxfix (certified SIF).

-- Step 1: New enums
CREATE TYPE "ReceiptStatus" AS ENUM ('DRAFT', 'PENDING', 'PAID', 'FAILED', 'CANCELLED', 'REFUNDED');
CREATE TYPE "ReceiptType" AS ENUM ('SUBSCRIPTION', 'RENTAL_COMMISSION', 'ADJUSTMENT', 'SETUP_PACKAGE', 'CONSUMABLES_ADDON', 'LAUNDRY_SERVICE', 'WELCOME_KIT', 'MAINTENANCE_FEE', 'REFUND');
CREATE TYPE "ExportStatus" AS ENUM ('DRAFT', 'GENERATED', 'UPLOADED_TO_TAXFIX', 'INVOICES_RECEIVED', 'COMPLETE');

-- Add new payment methods to existing PaymentMethod enum
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'STRIPE_CARD';
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'SEPA_DEBIT';

-- Step 2: TaxfixExport table
CREATE TABLE "TaxfixExport" (
  "id"                       TEXT NOT NULL,
  "exportNumber"             TEXT NOT NULL,
  "periodStart"              TIMESTAMP(3) NOT NULL,
  "periodEnd"                TIMESTAMP(3) NOT NULL,
  "totalReceipts"            INTEGER NOT NULL,
  "totalGrossAmount"         DECIMAL(10,2) NOT NULL,
  "totalVatAmount"           DECIMAL(10,2) NOT NULL,
  "totalNetAmount"           DECIMAL(10,2) NOT NULL,
  "exportFileUrl"            TEXT,
  "exportedAt"               TIMESTAMP(3),
  "exportedById"             TEXT NOT NULL,
  "status"                   "ExportStatus" NOT NULL DEFAULT 'DRAFT',
  "importedToTaxfixAt"       TIMESTAMP(3),
  "taxfixInvoicesGenerated"  BOOLEAN NOT NULL DEFAULT false,
  "createdAt"                TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"                TIMESTAMP(3) NOT NULL,
  CONSTRAINT "TaxfixExport_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "TaxfixExport_exportNumber_key" ON "TaxfixExport"("exportNumber");

-- Step 3: PaymentReceipt table
CREATE TABLE "PaymentReceipt" (
  "id"                    TEXT NOT NULL,
  "receiptNumber"         TEXT NOT NULL,
  "type"                  "ReceiptType" NOT NULL DEFAULT 'SUBSCRIPTION',
  "clientId"              TEXT NOT NULL,
  "propertyId"            TEXT,
  "createdById"           TEXT NOT NULL,
  "description"           TEXT NOT NULL,
  "grossAmount"           DECIMAL(10,2) NOT NULL,
  "discountAmount"        DECIMAL(10,2) NOT NULL DEFAULT 0,
  "netAmount"             DECIMAL(10,2) NOT NULL,
  "vatRate"               DECIMAL(5,2) NOT NULL DEFAULT 21,
  "vatAmount"             DECIMAL(10,2) NOT NULL,
  "totalAmount"           DECIMAL(10,2) NOT NULL,
  "currency"              TEXT NOT NULL DEFAULT 'EUR',
  "periodStart"           TIMESTAMP(3),
  "periodEnd"             TIMESTAMP(3),
  "reservationId"         TEXT,
  "status"                "ReceiptStatus" NOT NULL DEFAULT 'PENDING',
  "isAutoGenerated"       BOOLEAN NOT NULL DEFAULT false,
  "dueDate"               TIMESTAMP(3),
  "paidAt"                TIMESTAMP(3),
  "paymentMethod"         "PaymentMethod",
  "stripePaymentIntentId" TEXT,
  "stripeChargeId"        TEXT,
  "externalFiscalRef"     TEXT,
  "externalFiscalDate"    TIMESTAMP(3),
  "taxfixExported"        BOOLEAN NOT NULL DEFAULT false,
  "taxfixExportId"        TEXT,
  "notes"                 TEXT,
  "createdAt"             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"             TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PaymentReceipt_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "PaymentReceipt_receiptNumber_key" ON "PaymentReceipt"("receiptNumber");
CREATE UNIQUE INDEX "PaymentReceipt_stripePaymentIntentId_key" ON "PaymentReceipt"("stripePaymentIntentId");
CREATE INDEX "PaymentReceipt_clientId_idx" ON "PaymentReceipt"("clientId");
CREATE INDEX "PaymentReceipt_status_idx" ON "PaymentReceipt"("status");
CREATE INDEX "PaymentReceipt_type_idx" ON "PaymentReceipt"("type");
CREATE INDEX "PaymentReceipt_receiptNumber_idx" ON "PaymentReceipt"("receiptNumber");

ALTER TABLE "PaymentReceipt"
  ADD CONSTRAINT "PaymentReceipt_clientId_fkey"
  FOREIGN KEY ("clientId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PaymentReceipt"
  ADD CONSTRAINT "PaymentReceipt_propertyId_fkey"
  FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "PaymentReceipt"
  ADD CONSTRAINT "PaymentReceipt_createdById_fkey"
  FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "PaymentReceipt"
  ADD CONSTRAINT "PaymentReceipt_reservationId_fkey"
  FOREIGN KEY ("reservationId") REFERENCES "Reservation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "PaymentReceipt"
  ADD CONSTRAINT "PaymentReceipt_taxfixExportId_fkey"
  FOREIGN KEY ("taxfixExportId") REFERENCES "TaxfixExport"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Step 4: Migrate data from Invoice → PaymentReceipt (if Invoice table exists)
DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'Invoice') THEN
    INSERT INTO "PaymentReceipt" (
      "id", "receiptNumber", "type", "clientId", "propertyId", "createdById",
      "description", "grossAmount", "discountAmount", "netAmount",
      "vatRate", "vatAmount", "totalAmount", "currency",
      "status", "isAutoGenerated", "dueDate", "paidAt", "notes",
      "createdAt", "updatedAt"
    )
    SELECT
      i."id",
      'HM-' || EXTRACT(YEAR FROM i."createdAt")::TEXT || '-' || LPAD(ROW_NUMBER() OVER (ORDER BY i."createdAt")::TEXT, 4, '0'),
      CASE i."type"
        WHEN 'RENTAL' THEN 'RENTAL_COMMISSION'::"ReceiptType"
        WHEN 'SUBSCRIPTION' THEN 'SUBSCRIPTION'::"ReceiptType"
        WHEN 'ADJUSTMENT' THEN 'ADJUSTMENT'::"ReceiptType"
        ELSE 'ADJUSTMENT'::"ReceiptType"
      END,
      i."clientId",
      i."propertyId",
      i."createdById",
      i."description",
      i."amount",
      0,
      i."amount",
      21,
      ROUND(i."amount" * 21 / 121, 2),
      i."amount",
      i."currency",
      CASE i."status"::TEXT
        WHEN 'DRAFT' THEN 'DRAFT'::"ReceiptStatus"
        WHEN 'SENT' THEN 'PENDING'::"ReceiptStatus"
        WHEN 'PAID' THEN 'PAID'::"ReceiptStatus"
        WHEN 'CANCELLED' THEN 'CANCELLED'::"ReceiptStatus"
        ELSE 'PENDING'::"ReceiptStatus"
      END,
      i."isAutoGenerated",
      i."dueDate",
      i."paidAt",
      i."notes",
      i."createdAt",
      i."updatedAt"
    FROM "Invoice" i;

    -- Step 5: Drop old Invoice table and enums
    DROP TABLE "Invoice";
    DROP TYPE IF EXISTS "InvoiceStatus";
    DROP TYPE IF EXISTS "InvoiceType";
  END IF;
END $$;
