#!/bin/bash
# Exports HostMasters documentation for NotebookLM
# Usage: bash scripts/export-docs.sh

OUT="docs-notebooklm"
mkdir -p "$OUT"

echo "📄 Exporting HostMasters docs to $OUT/ ..."

# ── 1. Visão geral do produto ─────────────────────────────────────────────────
cat .claude/commands/hm.md > "$OUT/01-produto-visao-geral.md"
echo "✓ 01-produto-visao-geral.md"

# ── 2. Contexto técnico ───────────────────────────────────────────────────────
cat CLAUDE.md > "$OUT/02-contexto-tecnico.md"
echo "✓ 02-contexto-tecnico.md"

# ── 3. Modelo de dados (schema) ───────────────────────────────────────────────
cat > "$OUT/03-modelo-de-dados.md" << 'SCHEMA_EOF'
# HostMasters — Modelo de Dados (Prisma Schema)

Este ficheiro descreve todas as entidades da base de dados e as suas relações.

SCHEMA_EOF
cat prisma/schema.prisma >> "$OUT/03-modelo-de-dados.md"
echo "✓ 03-modelo-de-dados.md"

# ── 4. Fluxo financeiro ───────────────────────────────────────────────────────
cat > "$OUT/04-fluxo-financeiro.md" << 'FIN_EOF'
# HostMasters — Fluxo Financeiro e Planos

## Planos e taxas

| Plano   | Comissão | Mensalidade | Taxa limpeza                        | Diferencial                          |
|---------|----------|-------------|-------------------------------------|--------------------------------------|
| STARTER | 22%      | €0          | €70/saída (sempre)                  | Base — sem manutenção incluída       |
| BASIC   | 20%      | €89/mês     | €60/saída (sempre)                  | Manutenção preventiva, relatório multilingue |
| MID     | 17%      | €159/mês    | €45 se <5 noites / incluída ≥5 noites | AI pricing + Smart Lock            |
| PREMIUM | 13%      | €269/mês    | €35 se <3 noites / incluída ≥3 noites | Fiscal (Modelo 179 + IRNR), upsells |

## Fluxo de um pagamento

```
Hóspede paga Airbnb/Booking
        ↓
Plataforma deposita no banco (valor bruto)
        ↓
Admin cria Payout
  ├── grossAmount = valor recebido da plataforma
  ├── commission  = gross × taxa do plano do owner
  └── netAmount   = gross − commission
        ↓
Admin clica "Mark Paid"
  ├── paidAt = agora
  ├── Invoice criado automaticamente (isAutoGenerated=true)
  ├── Email "Owner Statement" enviado ao proprietário
  └── Email "Payment confirmed" de confirmação
        ↓
Dashboard actualiza (auto-refresh 60s)
```

## Datas de payout por plataforma

| Plataforma | Regra |
|-----------|-------|
| Airbnb | Checkout + 1 dia + 2 dias úteis |
| Booking.com | Último dia do mês do checkout |
| Direct / Other | Checkout + 7 dias |

## O que conta como receita HostMasters

✅ Comissões de arrendamentos (payout.commission WHERE PAID)
✅ Invoices manuais (isAutoGenerated=false, status=PAID)

❌ payout.grossAmount (dinheiro do owner, só passa pela plataforma)
❌ Invoices isAutoGenerated=true (registos contabilísticos, não receita HM)

## Relatório mensal automático

Cron job activo: dia 1 de cada mês, 08:00 UTC
- Calcula financeiros do mês anterior por propriedade
- Envia email com breakdown ao owner
- Guarda MonthlyReport.sentAt para evitar duplicados
FIN_EOF
echo "✓ 04-fluxo-financeiro.md"

# ── 5. Os 4 roles e portais ───────────────────────────────────────────────────
cat > "$OUT/05-roles-e-portais.md" << 'ROLES_EOF'
# HostMasters — Os 4 Roles e Portais

## Visão geral

| Role    | Portal  | URL          | Acesso |
|---------|---------|--------------|--------|
| ADMIN   | Admin   | `/`          | Tudo — payouts, invoices, marketing, AI, integrações, equipa |
| MANAGER | Manager | `/manager`   | Carteira própria (clientes com managerId=me), invoices, mensagens |
| CREW    | Crew    | `/crew`      | Tarefas operacionais, checklist, relatório de checkout |
| CLIENT  | Client  | `/client`    | Dashboard pessoal, ganhos, reservas, plano, AI (MID/PREMIUM) |

## ADMIN

Acesso total à plataforma. Cria utilizadores, aprova propriedades, emite payouts e invoices, vê todas as métricas.

### Funcionalidades do Admin
- **Dashboard** — Métricas em tempo real (volume, comissão, invoices pagos, receita total)
- **Properties** — Gestão com fluxo: PENDING_CLIENT → PENDING_APPROVAL → ACTIVE
- **Payouts** — Criação manual/automática, Mark Paid gera invoice + envia email
- **Invoices** — CRUD completo, tipos: RENTAL / SUBSCRIPTION / ADJUSTMENT
- **Calendar** — Reservas e bloqueios por propriedade
- **Team** — Gestão de utilizadores por role
- **CRM** — Pipeline de leads com score BANT, atribuição a campanhas
- **Marketing** — Campanhas com budget tracking, CPL por canal, registo de spend
- **Reports** — Relatórios financeiros por propriedade/mês, download PDF
- **AI Pricing** — Analytics de PricingDataPoint (dados recolhidos a cada reserva)
- **Integrations** — Roadmap: PriceLabs, Nordigen, Meta Ads, Brevo

## MANAGER

Vê apenas os clientes que lhe estão atribuídos (managerId). Acesso ao portal Admin mas dados filtrados.

### Funcionalidades do Manager
- Dashboard com métricas filtradas (só os seus owners)
- Clientes — lista e detalhe dos owners da sua carteira
- Reservas e calendário filtrados
- Tarefas operacionais
- Invoices dos seus clientes
- Mensagens com owners
- Fornecedores (suppliers) — directório de prestadores
- CRM — pipeline de leads (os seus)

## CREW

Acesso operacional. Foco em tarefas.

### Funcionalidades do Crew
- Lista de tarefas com filtros: hoje / abertas / concluídas
- Checklist interactivo (toggle por item, progresso em %)
- Relatório de checkout: condição (good / minor / major), danos, notas
- Calendar operacional

## CLIENT (Owner)

Proprietário do imóvel. Vê apenas os dados das suas propriedades.

### Funcionalidades do Client
- **My Home** — Dashboard pessoal com KPIs da(s) propriedade(s)
- **My Earnings** — Ganhos históricos, comissões, breakdown mensal
- **My Bookings** — Reservas activas e passadas
- **Care** — Pedidos de manutenção
- **My Plan** — Plano actual, comparação, upgrade via email
- **Contact us** — Mensagens directas com o Manager
- **AI Pricing** *(só MID/PREMIUM)* — Gráfico de sazonalidade com dados próprios

## Fluxo de criação de utilizadores

1. Admin vai a `/team`
2. Cria utilizador com role (MANAGER/CREW/CLIENT)
3. Se CLIENT: atribui propriedade ao owner
4. Se MANAGER: o manager fica disponível para atribuição a CLIENTs

## Hierarquia

```
ADMIN
  └── MANAGER (managerId → manager atribuído ao CLIENT)
        └── CLIENT (owner da propriedade)
CREW (operacional, sem hierarquia de gestão)
```
ROLES_EOF
echo "✓ 05-roles-e-portais.md"

# ── 6. Operações do dia-a-dia ─────────────────────────────────────────────────
cat > "$OUT/06-operacoes-dia-a-dia.md" << 'OPS_EOF'
# HostMasters — Operações do Dia-a-Dia

## Ciclo de uma reserva

### 1. Reserva entra (Airbnb/Booking/Direct)
- Admin ou Manager cria a reserva em `/reservations`
- Sistema gera automaticamente:
  - Tarefas: CHECK_IN, CHECK_OUT, CLEANING
  - PricingDataPoint por noite (dados para AI)
  - Payout agendado com data calculada por plataforma

### 2. Antes do check-in
- Crew recebe tarefa CHECK_IN
- Crew faz checklist de preparação
- Smart lock configurado (se MID/PREMIUM)

### 3. Checkout
- Crew recebe tarefa CHECK_OUT + CLEANING
- Crew preenche relatório: condição (good/minor/major), danos, notas
- Admin recebe notificação se condição for "major"

### 4. Payout
- Admin vê payout agendado no dashboard
- Admin clica "Mark Paid"
- Owner recebe email com statement (gross/commission/net)
- Dashboard actualiza métricas

### 5. Relatório mensal (automático)
- Dia 1 do mês às 08:00 UTC
- Sistema calcula mês anterior por propriedade
- Email enviado ao owner com breakdown financeiro
- Owner pode ver detalhe em `/client/reports`

## Tipos de tarefas

| Tipo | Quem executa | Quando |
|------|-------------|--------|
| CLEANING | Crew | Após cada checkout |
| MAINTENANCE_PREVENTIVE | Crew/Supplier | Mensal (BASIC+) |
| MAINTENANCE_CORRECTIVE | Supplier | A pedido |
| INSPECTION | Crew/Manager | Pré e pós estadia |
| CHECK_IN | Crew | Dia de entrada |
| CHECK_OUT | Crew | Dia de saída |
| SHOPPING | Crew | Pré-chegada (PREMIUM) |
| LAUNDRY | Crew | Pós-checkout (PREMIUM) |

## Gestão de fornecedores

- Directório em `/manager/suppliers`
- Tipos: CLEANER, PLUMBER, ELECTRICIAN, GENERAL
- Associados a propriedades específicas
- Contacto directo (Call / Email) a partir da ficha

## CRM — Pipeline de leads

### Stages
NEW → FIRST_CONTACT → CALL_SCHEDULED → QUALIFIED → PROPOSAL_SENT → CONTRACT_SIGNED → ACTIVE_OWNER

### Qualificação BANT
- **Budget** — Tamanho da propriedade (1 bed, 2 bed, 3+ bed)
- **Authority** — Decisor (sole owner, co-owner, POA)
- **Need** — Disponibilidade anual (meses/ano)
- **Timeline** — Quando quer começar
- **Location** — Costa Tropical, zona adjacente, fora da zona

Score máximo: 100 pontos. Lead qualificado a partir de 60+.

## Alertas e auto-refresh

- Dashboard admin: refresh a cada 60s + quando janela ganha foco
- Dashboard manager: refresh a cada 5 min
- Alerta visual para: tarefas em atraso, payouts pendentes
OPS_EOF
echo "✓ 06-operacoes-dia-a-dia.md"

# ── 7. Stack técnico ──────────────────────────────────────────────────────────
cat > "$OUT/07-stack-tecnico.md" << 'TECH_EOF'
# HostMasters — Stack Técnico

## Tecnologias principais

| Camada | Tecnologia |
|--------|-----------|
| Framework | Next.js 14 App Router + TypeScript |
| Base de dados | PostgreSQL (Neon) via Prisma ORM |
| Auth | NextAuth.js com JWT (roles na sessão) |
| Email | Resend (transacional) |
| Pagamentos | Stripe (subscrições + invoices) |
| Hosting | Vercel (deploy automático a cada push para main) |
| Testes | Vitest (27 unit tests em src/__tests__/) |
| PDF | jsPDF + jspdf-autotable |

## Deploy

```
git push origin main
  → Vercel detecta
  → prisma db push (sync schema)
  → next build
  → deploy automático
```

## Variáveis de ambiente necessárias

- DATABASE_URL — Neon PostgreSQL connection string
- NEXTAUTH_SECRET — segredo para JWT
- RESEND_API_KEY — API key do Resend
- STRIPE_SECRET_KEY — Stripe payments
- CRON_SECRET — protege o endpoint de cron mensal
- NEXT_PUBLIC_APP_URL — URL da aplicação (para links em emails)

## Cron jobs activos

| Job | Schedule | Função |
|-----|----------|--------|
| /api/cron/monthly-statements | 0 8 1 * * | Envia relatórios mensais a todos os owners |

## Regras críticas (nunca violar)

1. **Moeda**: base EUR. `useCurrency()` é só display — nunca em inputs de valor real
2. **subscriptionPlan**: não está na sessão — sempre ler da DB
3. **Comissões**: nunca hardcodar — usar `PLAN_COMMISSION` de `src/lib/finance.ts`
4. **Invoices auto-gerados**: `isAutoGenerated=true` — não contam como receita HM
5. **Migrations**: não usar `db push` em produção (usar `migrate deploy`) — EXCEPTO neste projecto que usa `db push` via Vercel

## Roadmap técnico

### Q2 2026 (em curso)
- PriceLabs API — pricing dinâmico para MID/PREMIUM
- Colecção de dados próprios via PricingDataPoint

### Q3–Q4 2026
- Nordigen/GoCardless — Open Banking (detecção automática de pagamentos)
- Stripe webhooks — subscrições automáticas
- Meta Ads API — sync de spend e CAC
- Brevo — nurturing de leads

### Longo prazo
- Modelo AI próprio treinado nos dados da plataforma
TECH_EOF
echo "✓ 07-stack-tecnico.md"

# ── Zip tudo ──────────────────────────────────────────────────────────────────
zip -r docs-notebooklm.zip "$OUT/" -x "*.DS_Store"
echo ""
echo "✅ Pronto!"
echo ""
echo "Ficheiros gerados em docs-notebooklm/:"
ls -1 "$OUT/"
echo ""
echo "Zip: docs-notebooklm.zip (faz upload deste para o NotebookLM)"
